### ISSUE TITLE
No native Web Assembly (wasm) support detected in Cordova app

### ISSUE THREAD

**Issue by flavioeverardo** [apache/cordova#100]
# Bug Report

## Problem

Cordova is running my application normally when the target is a browser but no native wasm support is detected when the target is iOS. Despite currently this is an iOS bug/problem, I'm reporting this here because I expect to further deploy the application to Android hoping that the same solution fits both.

### What is expected to happen?
You can try the application hosted on my server http://www.flavioeverardo.com/clingo/ where with a simple click on the run button, the Answer Set Programming (ASP) solver 'clingo' (which was compiled into wasm) solves the given problem.

A normal output would be something like this:
```
clingo version 5.3.1
Reading from stdin
Solving...
Answer: 1
motive(harry) motive(sally) guilty(harry) innocent(sally)
SATISFIABLE

Models       : 1
Calls        : 1
Time         : 0.001s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.000s
```

As mentioned before, running the same files locally when targeting the browser in cordova, gives a similar output as the one shown above. Everything works fine on browsers like Firefox, Chrome or Safari. You can also run the application from the link above in your phone browsers normally.

### What does actually happen?

When targeting into iOS (and I guess the same happens with Android but I have not tried it yet), the run button is disabled because all the dependencies are not fully loaded. The message shown is:
```
no native wasm support detected
```
I have tried it in the simulator running an iPhone 6s as well as in my iPhone (which is also an iPhone 6s) running iOS 12.2. I tried different simulators and deployment targets from 9.3 to 12.1 without success including physical devices.

### Command or Code

It works with: ```cordova run browser --target=Firefox/Chrome```
It does not work with ```cordova run ios [--target="iPhone-6s]"```

### Environment, Platform, Device

```
$ cordova platform ls
Installed platforms:
  browser 6.0.0
  ios 5.0.1
```

No plugins installed/used.

### Version information

Running macOS High Sierra version 10.13.6

Currently I cannot think on any other relevant feature to include here but if you need additional information, let me know. 

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
Cordova uses a webview to run your apps on iOS and Android. 
Do the webview implementations currently available there support wasm?

**Comment by timbru31** [comment]
Could you try it with the WKWebView plugin, too? @flavioeverardo  
It could be that this API is only exposed there. (From looking at caniuse WASM support should be in iOS 11+)

**Comment by flavioeverardo** [comment]
@timbru31 I tried this WKWebView plugin:
https://www.npmjs.com/package/cordova-plugin-wkwebview-engine
I installed it with npm and I added the respective code in my config.xml file as stated and still it says that wasm is not supported. 
How can I know that indeed my cordova app is running WKWebView instead of UIWebView?
Should I use the ionic WebView? https://github.com/ionic-team/cordova-plugin-ionic-webview
Also, how can I be sure that cordova is running the proper iOS version?

For your information, I forgot to state that I have the iOS SDK 12.1.
The cordova version is 9.0.0 (cordova-lib@9.0.1)

Thanks again.

**Comment by timbru31** [comment]
> How can I know that indeed my cordova app is running WKWebView instead of UIWebView?

You should see something along this line in the Xcode log when you launch your app from there:

`2019-04-26 14:07:20.150249+0200 HelloCordova[9191:393930] Using WKWebView`

> Should I use the ionic WebView? ionic-team/cordova-plugin-ionic-webview

You can try both, the Ionic WebView is just a fork and renaming of the cordova-plugin-wkwebview-engine

---

My quick test showed that WASM support is not working in a Simulator either (using the regular Safari app) **but is working fine** on my iPhone XS with iOS 12.3 beta with the cordova-plugin-wkwebview-engine!
(I've tested your linked demo and https://webassembly.org/demo/)

**Comment by flavioeverardo** [comment]
Hi @timbru31 thanks again for your help.
Now I'm sure that my app is running WKWebView as shown in the Xcode console.
Initially, I had created the project, add the platforms and then add the plugin (with the additional lines in the config.xml). 
That threw some errors that the Info.plist file was missing and UIWebView was the default view shown in the Xcode console.
To correct this I had to remove the ios platform:
```cordova platform remove ios```
and afterwards add it again with the ```--save``` flag:
```cordova platform add ios --save```

Now the WKWebView is set as the default view. As you said, I had no luck to see the app working with the simulators. 
On the other hand, I'm glad that you tried a couple of options and they work with a device. Unfortunately, I don't have access to devices supporting iOS 12+. 
I will ask someone to test the app or ask someone to lend me a device to test it so we can close the issue.

Regards,
Flavio

**Comment by timbru31** [comment]
Awesome! I might find enough time tomorrow to test an iPad with iOS 11, too.

**Comment by flavioeverardo** [comment]
Hi @timbru31 have you got a chance to test it on iOS 11? 
I can share that fortunately I have the chance to recompile the binary to a asm.js instead of a wasm file. I have tested it with a UIWebView and it works. I imagine that it will work on WKWebView too. 
I also ran it into my old iPad (iOS 9.3) and works too. 
I have not tried it yet on devices with iOS 11 or 12+ but I hope to do it soon.

**Comment by timbru31** [comment]
I've tested:
* iOS Safari 10.3 - as expected: no WASM support 🔴 
* iOS 11.4.1 - Cordova app with WKWebView ✅ 
* iOS 11.4.1 - Safari ✅ 

Can we close this issue?

**Comment by flavioeverardo** [comment]
Yes sure... I guess we have enough material to close this issue.
Thanks @timbru31

**Comment by antonellopasella** [comment]
> I've tested:
> 
> * iOS Safari 10.3 - as expected: no WASM support 🔴
> * iOS 11.4.1 - Cordova app with WKWebView ✅
> * iOS 11.4.1 - Safari ✅
> 

Hi @brodybits, can you publish a sample report for that?
I can’t have a working solution

Thanks!

**Comment by ankit17737** [comment]
> I've tested:
> 
> * iOS Safari 10.3 - as expected: no WASM support 🔴
> * iOS 11.4.1 - Cordova app with WKWebView ✅
> * iOS 11.4.1 - Safari ✅
> 
> Can we close this issue?

Hi you mentioned * iOS 11.4.1 - Cordova app with WKWebView ✅ works but when I tried doing that my entire application stops working.
