### ISSUE TITLE
Does Cordova support Angular 7?

### ISSUE THREAD

**Issue by fiportdev** [apache/cordova#102]
We are building an Angular 7 mobile app that will be integrated with a third party hybrid app (using standard HTML/JS technology) over which we have no control. They will call our function/app by launching a Webview (and URL) to pass control to us. Our app/functions then almost like a but in the Webview.

Generally, this is not a problem but we are trying to take advantage of the native controls that Cordova provides in a Hybrid app or access to via .

Do you have a sample app or an example or a build process on how to do this?

 It seems that it works with vanilla HTML app but not with Angular 7 app.

Thanks

**Comment by raphinesse** [comment]
You can wrap any web app with Cordova. That also includes Angular apps.

Our issues are not for support requests. If you need help using Cordova, you should probably ask on [stackoverflow](https://stackoverflow.com/) or on our [slack](http://slack.cordova.io/).
