### ISSUE TITLE
[Plugins] Typings Versioning, Maintenance and Documentation

### ISSUE THREAD

**Issue by janpio** [apache/cordova#103]
Most of our plugins now have a `types` folder where we have typing for Typescript:

https://github.com/apache/cordova-plugin-statusbar/tree/master/types
https://github.com/apache/cordova-plugin-statusbar/blob/master/types/index.d.ts

This is useful, especially in the context of Ionic and Angular. @timbru31 is our typings expert, and takes on the role of keeping those up to date and is their "owner" more or less. here is an issue tracking that work: https://github.com/apache/cordova/issues/39

But I have some questions regarding Versioning, Maintenance and Documentation:

1.

- In https://github.com/apache/cordova-plugin-statusbar/pull/132 the question came up of including the plugin version number in the typings themselves. Do we actually need to do that, when we host the typings ourselves? Updating those version numbers would add an extra step to the release process (and surely be forgotten from time to time). So if they are not _needed_ for our self hosted typings, I would rather leave them out.

2. Also:

- Are there tools to create these typings automatically?
- Are there tools to check if the typings are current and valid somehow?

3. We need some documentation that is more than "ask @timbru31" so that we can properly support those typings as part of our core plugins, and maybe even give guidance to plugin authors why and how to include them in theirs. Should this live in the general plugin documentation in our main docs?

**Comment by brodybits** [comment]
> * In [apache/cordova-plugin-statusbar#132](https://github.com/apache/cordova-plugin-statusbar/pull/132) the question came up of including the plugin version number in the typings themselves.
> [...]

I would personally downvote that idea. I think that dependent code should be able to code to the interface without regard to what version of the plugin it is using.

> * Are there tools to create these typings automatically?

If the source code is JSDoc annotated, I have seen some tools that will generate the `.d.ts`:

- https://github.com/englercj/tsd-jsdoc
- https://github.com/otris/jsdoc-tsd
- https://github.com/fivetran/typescript-closure-tools (Closure being a style of JSDoc)

I would generally favor using JSDoc with types for the multiple benefits of maintainability, clarity, and [Type Safe JavaScript with JSDoc](https://medium.com/@trukrs/type-safe-javascript-with-jsdoc-7a2a63209b76) (article by @rbiggs).

**Comment by janpio** [comment]
> I think that dependent code should be able to code to the interface without regard to what version of the plugin it is using.

My formulation might not have been clear enough: The version number is only included in a comment at the beginning of the file, to indicate which version the definitions apply to. 

Disadvantage is that this creates a new mandatory release step because that number of course has to be incremented with each release.

**Comment by raphinesse** [comment]
Well, I agree that such a comment should not exist since naturally the typings in the plugin package apply to the version of the plugin that is in the package which is the version of the package. Easy :)

**Comment by BBosman** [comment]
For definitions hosted on DefinitelyTyped it makes sense to add a version number, because there is a loose coupling with the code. You can update those packages independently. 

In the situation where the definitions are part of the code repo/packages it does not make sense to add a version number, as there is a hard link with the version of the code in that same package.

So in the Cordova case I would go for not having a version number in there.

**Comment by janpio** [comment]
Just went through all our plugins with types and removed the plugin version numbers.
