### ISSUE TITLE
Compiled Cordova app unexpectedly closes after about a week on iOS device

### ISSUE THREAD

**Issue by sts-ryan-holton** [apache/cordova#109]
# Bug Report

## Problem

My compiled Cordova app appears to crash when opening and quits unexpectedly after about a week since I made the app, this is on iOS and using Cordova 9

### What is expected to happen?

App should remain functional after a week

### What does actually happen?

App randomly quits upon opening on iOS

## Information

- Cordova 9.x
- iOS 12.3
- Compiled Nuxt JS/Vue JS app for iOS
- Was working perfectly fine yesterday
- I've tried two custom built apps by me, seems the same on both, after a week on each opening they quit unexpectedly 

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
What does "quits unexpectedly" mean?
How did you build and install the app?
Did you look at any crash logs or other log files?

**Comment by sts-ryan-holton** [comment]
@janpio I open the app, and then it just randomly closes. It was fine yesterday, and I haven't done anything, it's been fine every day, but the pattern is this:

It seems to be after about a week, regardless of the app, it randomly quits on opening

**Comment by janpio** [comment]
How are you building your app? 
What kind of Apple developer account are you using to sign the app?

**Comment by sts-ryan-holton** [comment]
That sounds about right actually, I'm using a "Personal Team" Apple account (not paying), and this sounds about right.

**Comment by janpio** [comment]
Yes, that explains what you are seeing. Apple got quite restrictive to force people to use a paid Apple developer account (if personal or for a company doesn't matter, as long as you paid them some money so they have a valid billing address for you).
