### ISSUE TITLE
Cordova app unable to access external scripts on Android

### ISSUE THREAD

**Issue by lemacarl** [apache/cordova#116]
# Bug Report

### What is expected to happen?

Cordava app on Android should be able to access external scripts

### What does actually happen?

When I run the app on Android I get a `Refused to load script error...` in the console log. I am using Chrome Developer Tools to debug the WebView

## Information
I have installed `cordova-plugin-whitelist` and added `<access origin="*" />` to the `config.xml`. When I run the app in the browser I don't get any error and all the external scripts are loaded.

The error message that I get is:
```
Refused to load the script 'file://www.radiojar.com/wrappers/api-plugins/v1/player.js?1.65.1t' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' http://www.radiojar.com/wrappers/api-plugins/v1/player.js http://www.radiojar.com/wrappers/api-plugins/v1/jplayer/jplayer.js http://now-dot-playing-dot-radiojarcom.appspot.com/api/stations/u31u2awpxbwtv/now_playing/". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

### Command or Code
`cordova run android`

### Environment, Platform, Device
Cordova:
cordova (Cordova CLI) : 9.0.0
Cordova Platforms : android 8.0.0, ios 5.0.0
Cordova Plugins: cordova-plugin-splashscreen, cordova-plugin-dialogs, cordova-plugin-network-information, cordova-plugin-inappbrowser, cordova-plugin-whitelist

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by janpio** [comment]
What is the CSP of your app/site?
