### ISSUE TITLE
Will cordova support iPadOS?

### ISSUE THREAD

**Issue by hmr-it-jr** [apache/cordova#118]
Yesterday apple has introduced the new OS for iPads called "iPadOS".

Will iPadOS be supported by cordova?

[https://www.cnet.com/videos/apple-introduces-ipad-os/](https://www.cnet.com/videos/apple-introduces-ipad-os/)

**Comment by brodybits** [comment]
Yes so far: https://twitter.com/jcesarmobile/status/1135975882332487681

**Comment by jcesarmobile** [comment]
iPadOS is just iOS with a few more features, but iOS on iPad always had more features than on iPhones. We don't need to do anything to make iOS apps work on iPadOS
