### ISSUE TITLE
Run background jobs

### ISSUE THREAD

**Issue by dariosalvi78** [apache/cordova#120]
# Feature Request

## Motivation Behind Feature
Currently, there is no way to schedule code execution in the background in Cordova apps.
Android supports this through [jobs](https://www.vogella.com/tutorials/AndroidTaskScheduling/article.html) and iOS [is going to support this functionality too](https://developer.apple.com/documentation/backgroundtasks) soon.
In browsers, one could use service workers (which are not available in Webviews) and in desktops, one could use other native systems ([Windows](https://docs.microsoft.com/en-us/windows/desktop/taskschd/task-scheduler-start-page) and [MacOS](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/ScheduledJobs.html))

## Feature Description
The feature would allow to schedule future execution of JS code, in background, while having access to global variables and plugins, like it was running on the webview, but without access to the DOM.
An example of the code could be:

```js
cordova.backgroundSchedule({
  requiresNetwork: true,
  requiresExternalPower: false,
  when: new Date() // some time in the future
  }, function () {
  // my code here has access to the plugins
})
```

## Alternatives or Workarounds
I don't know if this idea would fit better as a new plugin or as a platform-wise feature.

Running JS code in iOS outside of the Webview is possible through the [JavaScriptCore](https://developer.apple.com/documentation/javascriptcore), while in Android, there are [a bunch of alternatives](https://medium.com/tech-quizlet/comparison-shopping-searching-for-javascript-engines-for-android-bdc656538f2e).
Same applies for Desktop ([Windows](https://stackoverflow.com/questions/5742128/javascript-standalone-compiler-or-interpreter-for-windows) and [MacOS](https://developer.apple.com/documentation/javascriptcore)).

Currently, the only way to execute background code is through [this plugin](https://github.com/katzer/cordova-plugin-background-mode), but it comes with limitations (e.g. execution cannot be scheduled).

**Comment by janpio** [comment]
This definitely is a candidate for a plugin (as it is only needed by some users, also a new API that will probably need some iteration) - but a very interesting one.

**Comment by dariosalvi78** [comment]
it looks like [this](https://github.com/transistorsoft/cordova-plugin-background-fetch) plugin implements what I requested.
I haven't tried it yet though.
