### ISSUE TITLE
[Plugins] Convert to eslint

### ISSUE THREAD

**Issue by janpio** [apache/cordova#123]
Some plugins are still using jshint or no linting at all. Those should be converted to use eslint as most Cordova core plugins already do.

To convert:
- [ ] https://github.com/apache/cordova-plugin-media/issues/233
- [ ] https://github.com/apache/cordova-plugin-splashscreen/issues/219
- [ ] https://github.com/apache/cordova-plugin-statusbar/issues/141
- [ ] https://github.com/apache/cordova-plugin-screen-orientation/issues/50

**Comment by GedasGa** [comment]
Cordova-plugin-screen-orientation does have `jshint`.

**Comment by janpio** [comment]
Updated the TODO (and linked issues) per your comment

**Comment by breautek** [comment]
Closing in favour of a much more progressed tracking ticket at https://github.com/apache/cordova/issues/142
