### ISSUE TITLE
How to use Animation and materialise UI Using cordova as android for Hybrid app.

### ISSUE THREAD

**Issue by devopsexpro** [apache/cordova#125]
I have developed Hybrid App using Cordova apache for Android .in that I have used PHP in backend and frontend is html5 CSS, javascript, my app is work in android. but when I use animation or materialize frontend Template.it is not working in a hybrid app using Cordova as android ..Why?? please brief and Inform how do I implement it..Kindly Inform

**Comment by timbru31** [comment]
Our issues here are not intended for support requests. If you need any further help using Cordova, you should probably ask on [StackOverflow](https://stackoverflow.com/) or on our [Slack](http://slack.cordova.io/).
