### ISSUE TITLE
cordova -v command display bug

### ISSUE THREAD

**Issue by justwezzz** [apache/cordova#137]
![捕获](https://user-images.githubusercontent.com/1901634/60602892-46107280-9de7-11e9-9ea6-2a28578d20bf.PNG)

after update cordova，the cordova -v command still display old version。

**Comment by janpio** [comment]
What does `npm list -g --depth=0` return?

**Comment by justwezzz** [comment]
@janpio 
![1](https://user-images.githubusercontent.com/1901634/60632251-39b40600-9e37-11e9-998a-d391eadf966d.png)

**Comment by janpio** [comment]
And `cordova -v` still returns the wrong version? That is really strange.

Can you post the beginning of your `cordova info` output please? (Run it in a newly created project, `cordova create`)

**Comment by justwezzz** [comment]
@janpio 
![1](https://user-images.githubusercontent.com/1901634/60722600-03c07000-9f64-11e9-95dc-5a73fea97181.png)

**Comment by raphinesse** [comment]
I guess you have multiple Cordova installations and an old one has precedence over the one installed and listed by `npm -g`. Check `where cordova` and correct the contents of `%PATH%` if necessary.

**Comment by justwezzz** [comment]
@raphinesse you are right,I find two cordova from my computer,but how can I switch the cordova to new version or uninstall the old version(I try to use npm uninstall -g cordova,but not work)
![1](https://user-images.githubusercontent.com/1901634/60763373-c3690b00-a0a5-11e9-997e-12a1af85d6ad.png)
![2](https://user-images.githubusercontent.com/1901634/60763374-c6fc9200-a0a5-11e9-99c9-4b283eca5e98.png)

**Comment by janpio** [comment]
You can probably just delete the folder. The cleanest solution would be to uninstall your current node and then reinstall it using a node manager like nvm-windows.

**Comment by justwezzz** [comment]
@janpio it works,after uninstall node and install nvm to install cordova,now cordova's version is right.thank you and @raphinesse .😀
