### ISSUE TITLE
Cordova never fires deviceready event

### ISSUE THREAD

**Issue by kristijan97** [apache/cordova#139]
# Bug Report
Cordova app is sucessfully build but I never get a deviceready event, which means that I cannot use its plugins like firebase. There is one thing which I noticed, maybe it is important. windows element doesn't have attached prototype Firebase

### What does actually happen?
Everything works fine - app is build, signed and deployed on phone, but deviceready event never fires

## Information
main.js / App.vue :
```js
created() {
  setTimeout(() => { this.initCordova }, 10000); //test
  document.addEventListener('deviceready', this.initCordova);
}
methods: {
  initCordova() {
    alert('Initialized');
    window.FirebasePlugin.grantPermission();
   ...
  }
}
```

### Command or Code
    cordova build ios --release

### Version information
XCode 10.12.1
platform: ios 5.0.1
plugins:
cordova-plugin-firebase 2.0.5
cordova-plugin-whitelist 1.3.4

codebase: vue
npm 6.9.0
macOS Mojave
target phone: iPhone 4s & 7

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
This doesn't look like an issue with fastlane itself, but that plugin you are using. A plain Cordova app definitely does fire `deviceready` when the app is ready to be used. You should probably open an issue with the plugin.

**Comment by kristijan97** [comment]
I know, that's why I tested only with whitelist plugin (which is necessary for vue-router)

**Comment by janpio** [comment]
Run `cordova create MyApp`, then add a platform and run the app. The screen will show you when the deviceready event was fired.

**Comment by brodybits** [comment]
Is this still an issue?

Can you [make a reproduction for us](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md)?

**Comment by raphinesse** [comment]
Closing as necessary reproduction case has not been provided.
