### ISSUE TITLE
cannot access iframe content from another domain, XHR empty response text, access origin * and navigation * no longer functions properly

### ISSUE THREAD

**Issue by aymen157** [apache/cordova#144]
# Bug Report
disabling websecurity not working properly
## Problem
cordova does not allow the access to iframe, neither to get an XHRequest response from external websites

### What is expected to happen?
CORS + site isolation trials to be disabled 

### What does actually happen?
only a fraction of CORS was disabled xFrameOrigin is working fine, but cannot retreive the iframe content (elements)

### Environment, Platform, Device

Tested on :
Windows
Android

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
CORS protocol is not something that can be disabled at this time. You'll need to ask Google to provide and API to disable CORs.
