### ISSUE TITLE
Cordova "Apple will stop accepting submissions of apps that use UIWebView" warning when submitting to app store

### ISSUE THREAD

**Issue by sts-ryan-holton** [apache/cordova#148]
# Bug Report

## Problem

I'm building a hybrid app for both iOS and Android. The app primarily is built using [Nuxt JS](https://nuxtjs.org/), a Javascript based Vue JS framework, along with [Vuetify JS](https://v15.vuetifyjs.com/en/). I'm using Cordova 8.0.0 currently to build and compile my app and have recently submitted our first ever app to the app store for review, I have recieved back a depreciation warning and am concerned that this isn't going to be fixed in Cordova?

```
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
```
I'm using very few Cordova plugins, and am wondering whether this issue has been addressed, or is related to one of my Cordova based plugins listed below.

### What is expected to happen?

The depreciation warning shouldn't appear when submitting to the app store from a Cordova project.

### What does actually happen?

The warning appears.

## Information

NPM version: 6.10.2
Node version: 10.13.0
Xcode: 10.3

I'm building for iOS 12.4, with a deployment target of 10.0

I'm using the following Cordova plugins and their versions:

```json
"dependencies": {
        "cordova-android": "^7.1.4",
        "cordova-ios": "^4.5.5",
        "cordova-plugin-actionsheet": "^2.3.3",
        "cordova-plugin-app-event": "^1.2.1",
        "cordova-plugin-background-mode": "^0.7.3",
        "cordova-plugin-badge": "^0.8.8",
        "cordova-plugin-console": "^1.1.0",
        "cordova-plugin-device": "^2.0.3",
        "cordova-plugin-local-notification": "git+https://github.com/katzer/cordova-plugin-local-notifications.git",
        "cordova-plugin-native-keyboard": "^2.0.3",
        "cordova-plugin-powermanagement-orig": "git+https://github.com/boltex/cordova-plugin-powermanagement.git",
        "cordova-plugin-whitelist": "^1.3.3"
    }
```

I'm using both iOS and Android for building, I'm using Nuxt JS 2.9.2

### Command or Code

The commands used to build the app are as follows:

```json
"scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "NODE_ENV=production nuxt generate",
    "cordova-ios": "NODE_ENV=production npm run build-spa && npm run replace-relative-paths && npm run copy-cordova && npm run run-ios;",
    "cordova-android": "NODE_ENV=production npm run build-spa && npm run replace-relative-paths && npm run copy-cordova && npm run run-android;",
    "cordova-browser": "NODE_ENV=production npm run build-spa && npm run replace-relative-paths && npm run copy-cordova && npm run run-browser;",
    "build-spa": "nuxt build --spa",
    "replace-relative-paths": "replace '/nuxtfiles/' 'nuxtfiles/' dist --recursive && replace '/assets/' 'nuxtfiles/' dist --recursive && replace '(href|src|\"href\"|\"src\")=\"/' '$1=\"../' dist --recursive && replace '(href|src|\"href\"|\"src\"):\"/' '$1:\"../' dist --recursive",
    "copy-cordova": "cp -R dist/* cordova/www/",
    "clear-cordova": "rm -R cordova/www/*",
    "run-ios": "cd cordova && cordova run ios --buildFlag='-UseModernBuildSystem=0' --target='iPhone-X, 12.2'",
    "run-android": "cd cordova && cordova run android",
    "run-browser": "cd cordova && cordova run browser"
  }
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
The discussion is happening here: https://github.com/apache/cordova-ios/issues/661 - and currently it is just a warning :)
