### ISSUE TITLE
bug: ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by shrivallabhDeshmukh** [apache/cordova#150]
Dear Team

I got below mail from apple after uploading app to testFlight

Dear Developer,
We identified one or more issues with a recent delivery for your app, "Michael Page FR" 1.0.0 (1.0.2). Your delivery was successful, but you may wish to correct the following issues in your next delivery:
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . Seehttps://developer.apple.com/documentation/uikit/uiwebview for more information.
After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.
Best regards,
The App Store Team

Please advice on this issue.
your early response in this regard would be highly appreciated.
Thank you

**Comment by breautek** [comment]
See https://github.com/apache/cordova-ios/issues/661

Long story short, there is no official solution yet. Some people have offered PRs to remove references of `UIWebView` which you can try at your own risk. Apple has given no official date of when they will actually start to reject apps still referencing `UIWebView`. At this current time, you can still submit and update apps using the `UIWebView`

However if you are using the `UIWebView`, which is the current default, then I'd recommend to start planning immediately to migrate to the [WkWebview](https://github.com/apache/cordova-plugin-wkwebview-engine). `WKWebView` migration could be a breaking change for you that you should be prepared for.

Additionally the [cordova-ios](https://github.com/apache/cordova-ios/issues) repo is a better place to raise issues for the specific platform.
