### ISSUE TITLE
Failed to run "javac -version", make sure that you have a JDK version 8 installed. (JDK 12)

### ISSUE THREAD

**Issue by domske** [apache/cordova#151]
# Bug Report

## Problem
Failed to run "javac -version", make sure that you have a JDK version 8 installed.

### What is expected to happen?
Just work, JDK 12 (openjdk) is installed correctly.
I can run the command on the console.
It should also work with 12, or not?

### What does actually happen?
It does not work. But the jdk is installed. Not 8, but 12.
Why is this a problem? Just try it.

## Information
The whole Android enviroment and JDK, Ionic, Cordova etc. are installed.
I can run Android apps on my physical phone. e.g. using Flutter and the Android Studio.
JAVA_HOME and PATH are set. [JDK](https://jdk.java.net/) 
`Requirements check failed for JDK 8 ('1.8.*')! Detected version: 12.0.2`
Why should JDK 12 not work?

### Command or Code
`ionic cordova run android`
`javac -version` // javac 12.0.2

### Environment, Platform, Device
Running Cordova 9 with native-run of Ionic 4 on Windows 10 64bit.

### Version information

<details>
  <summary>Click to expand</summary>
Ionic:

   Ionic CLI                     : 5.2.5
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0

Utility:

   cordova-res : not installed
   native-run  : 0.2.8

System:

   NodeJS : v10.16.3
   npm    : 6.9.0
   OS     : Windows 10
</details>

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

## Workaround

Install the Oracle JDK 1.8 (alias 8). Can't find it for OpenJDK. Whatever... I wondering why is the latest JDK not supported? Just try it. We will see if it fails.

**Comment by breautek** [comment]
Cordova requires JDK 8 because that is what the Android SDK requires. Major versions of any software generally means that there are breaking changes that must be refactored during a major version upgrade, so this is likely why the android SDK does not support JDK 12.

Additionally, platform specific questions are better off asked in their respective repo. In this case, [cordova-android](https://github.com/apache/cordova-android/issues) would be a better place to ask a question like this.
