### ISSUE TITLE
load cordova-android plugins on webserver

### ISSUE THREAD

**Issue by baptistapedro** [apache/cordova#153]
Hi,
Would like to ask you guys to follow this thread please and help me come up with a solution.

https://stackoverflow.com/questions/57963296/load-cordova-android-plugins-on-webserver

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support - and you already asked on StackOverflow and are active on our Slack, that should be enough ;)
