### ISSUE TITLE
git+ssh does not work for gitlab?

### ISSUE THREAD

**Issue by geertijewski** [apache/cordova#154]
# Problem
When adding plugins over git+ssh the behaviour seems to change based on which git host ist used.

## What is expected to happen?
Download works for all git hosts.

## What does actually happen?
Does not work for gitlab

### Command or Code
```sh
> cordova create com.example.org
> cd com.example.org/
> cordova plugin add git+https://github.com/petermetz/cordova-plugin-ibeacon.git
# works
> > cordova plugin add git+ssh://git@github.com:don/cordova-plugin-ble-central.git
(node:531) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin git+ssh://git@github.com:don/cordova-plugin-ble-central.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/don/cordova-plugin-ble-central.git
npm ERR! 
npm ERR! Warning: Permanently added 'github.com,140.82.118.3' (RSA) to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

...

> cordova plugin add git+ssh://git@gitlab.com:cordova-plugins/cordova-selectvalue.git
(node:875) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin git+ssh://git@gitlab.com:cordova-plugins/cordova-selectvalue.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! premature close
...
```

It seems like cordova correctly detects in both cases that this plugin is not in the NPM registry. But only for the github URL it acturally then tries to access it over git+ssh.

### Environment, Platform, Device
Ubuntu, x86_64

### Version information
```sh
> cordova --version
8.0.0
```

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
@geertijewski I would recommend updating to Cordova 9.x and try again. I recall something was done in the past for Cordova 9 with regards to fetching and git.

When I tried with the gitlab url you provided I see this.

```
...
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@gitlab.com/cordova-plugins/cordova-selectvalue.git
...
```

It appears to be correct and that the npm ERR is due to `Permission denied (publickey)`.

**Comment by raphinesse** [comment]
Closing after more than two months without reply from OP
