### ISSUE TITLE
Cordova not allowing beta versions of plugins to run, instead requiring full version numbers.

### ISSUE THREAD

**Issue by devleaf-matt** [apache/cordova#165]
# Bug Report

## Problem

When running `cordova run ios --device --verbose --target <IPHONE_TARGET>` after updating to MacOS 10.15 Catalina, cordova now returns: 
```
CordovaError: Promise rejected with non-error: 'Version should contain only numbers and dots'
    at cli.catch.err (/Users/devleaf.matt/.npm-global/lib/node_modules/cordova/bin/cordova:30:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
rather than going on to a successful IPA install and launch on my iPhone. After searching around it seems people have this problem with the google maps plugin, however I don't have this installed on my system. I have re-installed cordova, reinstalled cordova ios (platform removal and re-addition) and double checked my Cocoa pods version.

## Information

![2019-10-16 21 53 07](https://user-images.githubusercontent.com/49694881/66958933-3dc00880-f061-11e9-84c3-a7f89f6d6da7.gif)

![Screenshot 2019-10-16 at 22 12 54](https://user-images.githubusercontent.com/49694881/66959381-233a5f00-f062-11e9-8ab6-07df6a0ca091.png)

### Command or Code

`cordova run ios --device --verbose --target <IPHONE_TARGET>`

### Environment, Platform, Device

VS Code | Ionic 4 | MacOS Catalina | iMac | iPhone 11 Pro

### Version information

Cordova 8.1.2 (Lib 8.1.1)
XCode 11.1
Ionic 4 (CLI 5.4.4)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
`Version should contain only numbers and dots` seems to suggest there is a version somewhere that probably has a label such as a pre-release e.g. `1.2.3-beta.1`

Does any of your packages or plugins you have installed have a version format other than `x.y.z` format?

**Comment by devleaf-matt** [comment]
Hi Breautek, thanks for your quick response. I'll post below my plugin list in the config.xml, however I believe the problem to be the `<plugin name="cordova-plugin-local-notification" spec="^0.9.0-beta.3" />` plugin. I'll downgrade to 0.9.0 but is it possible to keep this plugin in the current beta as some features between 0.9.0 and beta.3 are not available?

![Screenshot 2019-10-18 at 18 55 02](https://user-images.githubusercontent.com/49694881/67116849-36236f80-f1d9-11e9-9b3b-6b12bf87890a.png)

**Comment by breautek** [comment]
I'll mark this as a bug. I think cordova should support prerelease labels. They are perfectly valid in the [semver](https://semver.org/) spec.

Meanwhile, a workaround could be installing the plugin from the git repo, assuming it is hosted in a git repo. You can install the plugin from git. e.g;
`cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications.git#0.9-beta.3`

Installing plugins from git should bypass semver version checks. Of course you lose out on automatic updating on minor/patch updates.

**Comment by devleaf-matt** [comment]
Hi Breautek. Thanks for marking this as a bug, I'll continue with the above method now using the direct GIT repo, and look out for an update in the future. Thanks for your rapid responses.

**Comment by devleaf-matt** [comment]
Sorry just as a quick note, I've now changed the plugin specs to match the following (see image below) and removed and re-added the Cordova ios and android platform, however, am still getting the same error code. Is there another place this check is performed other than just the plugins?

![Screenshot 2019-10-18 at 22 39 34](https://user-images.githubusercontent.com/49694881/67130080-37b06000-f1f8-11e9-829c-9fdd78b82895.png)

**Comment by devleaf-matt** [comment]
Hi breautek,

So i've tried adding the local notification plugin using the git repo rather than the conventional `cordova add <plugin>@latest` and it when running `cordova plugin list` i noticed it was still pulling 0.9.0-beta3 as it's name, unfortunately meaning there isn't a way to add the plugin without forking and changing the version number.

**Comment by breautek** [comment]
My bad, I thought it would bypass semver checks but it appears it still goes through them anyway.On Oct. 19, 2019 9:25 a.m., Matthew Milan <notifications@github.com> wrote:Hi breautek,
So i've tried adding the local notification plugin using the git repo rather than the conventional cordova add <plugin>@latest and it when running cordova plugin list i noticed it was still pulling 0.9.0-beta3 as it's name, unfortunately meaning there isn't a way to add the plugin without forking and changing the version number.

**Comment by raphinesse** [comment]
The error (that is not an `Error` :wink:) originates in [`cordova-ios`](https://github.com/apache/cordova-ios/blob/be68c9f6d49aff85a5f7a52ffcbfd31d5b018a90/bin/templates/scripts/cordova/lib/versions.js#L161-L194). That function should probably be updated to use `semver` to compare the versions. Unless there's a reason to only support a subset of semver.

The same code also seems to be copied to [`cordova-osx`](https://github.com/apache/cordova-osx/blob/7943ec9d3efc3b4d3c5da765988e60cb7f0c7250/bin/lib/versions.js#L107-L140).

I think PRs to fix this issue would be very welcome. If someone creates them, please request a review from me since I'm not watching those platform repos.

**Comment by devleaf-matt** [comment]
> The error (that is not an `Error` 😉) originates in [`cordova-ios`](https://github.com/apache/cordova-ios/blob/be68c9f6d49aff85a5f7a52ffcbfd31d5b018a90/bin/templates/scripts/cordova/lib/versions.js#L161-L194). That function should probably be updated to use `semver` to compare the versions. Unless there's a reason to only support a subset of semver.
> 
> The same code also seems to be copied to [`cordova-osx`](https://github.com/apache/cordova-osx/blob/7943ec9d3efc3b4d3c5da765988e60cb7f0c7250/bin/lib/versions.js#L107-L140).
> 
> I think PRs to fix this issue would be very welcome. If someone creates them, please request a review from me since I'm not watching those platform repos.

Hi Raphinesse, 

I'm sorry it's not the best fix in the world, the semver spec is quite dynamic and has that many variants that it would take a while to process fully (unfortunately I don't have too much time on my hands) however this allows beta/alpha variants to work properly (or so it seems in my testing). Hope this helps someone in the future!

**Comment by adminy** [comment]
I have nothing with beta versions but I am getting the same error. 
<img width="781" alt="Screenshot 2019-10-21 at 07 16 37" src="https://user-images.githubusercontent.com/22717869/67180883-d395c380-f3d2-11e9-8a2c-8bcbf9b2d2ec.png">

**Comment by devleaf-matt** [comment]
Hi adminy,

I noticed that a certain iOS plugin was running 1.10.0-beta3 even though no plugin I installed was of that version. To my knowledge, these plugins update near runtime in order to allow you to stay up to date so you won't know for sure. If you review my pull request above then modify that file in your local ios/osx setup then it will work as a temporary solution before I get the pull request submitted later today.

**Comment by adminy** [comment]
Thank you @devleaf-matt your pull request worked, except it wasn't the `bin/templates/scripts/cordova/lib/versions.js` file that I had to modify, it was the `platforms/ios/cordova/lib/versions.js` file, but I assume this is generated from the template file at installation time or some other time when stetted up. Keep up the good work

**Comment by sanyashvets** [comment]
Hi. I'm faced with same error few days ago. But I have no `beta` or smth else in versions.
Also, this error occurs when I'm trying to run/build project with connected device (iOS 13.1.3, 12.4.3, 12.4.2)
```
CordovaError: Promise rejected with non-error: 'Version should contain only numbers and dots'
    at /Users/alex/.nvm/versions/node/v12.12.0/lib/node_modules/cordova/bin/cordova:29:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios --device exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.


 ionic cordova plugin list
> cordova plugin ls
cordova-plugin-advanced-http 2.2.0 "Advanced HTTP plugin"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-camera-preview 0.11.0 "cordova-plugin-camera-preview"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
es6-promise-plugin 4.2.2 "Promise"
phonegap-plugin-barcodescanner 8.1.0 "BarcodeScanner"

```

**Comment by adminy** [comment]
@sanyashvets Just do what I did
