### ISSUE TITLE
video dosen't play in cordova android build but it playes fine in web!!

### ISSUE THREAD

**Issue by peymannaderi3** [apache/cordova#168]
# Bug Report

## Problem
i created a simple web app using cordova cli.
put a video tag in middle of the page.
when i serve the www folder it shows the video perfectly. the problem is when i build android app and install it on my phone.
it can't open the video!?
### What is expected to happen?
play the video as expected

### What does actually happen?
the video tag jus could load it.

### Command or Code

<video
        src="http://cdn.persiangig.com/preview/TSJ0PRnVo7/medium/WhatsApp_Video_2019-10-11_at_16.56.55.mp4"
        controls
      ></video>

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by peymannaderi3** [comment]
the video tag i put is here:
<video
        src="http://cdn.persiangig.com/preview/TSJ0PRnVo7/medium/WhatsApp_Video_2019-10-11_at_16.56.55.mp4"
        controls
      ></video>

**Comment by peymannaderi3** [comment]
<video
        src="my video link"
        controls
      ></video>

**Comment by peymannaderi3** [comment]
`<video
        src="http://cdn.persiangig.com/preview/TSJ0PRnVo7/medium/WhatsApp_Video_2019-10-11_at_16.56.55.mp4"
        controls
      ></video>`

**Comment by timbru31** [comment]
Please create the issue in the correct repository (e.g., cordova-android or a specific plugin repo); this one is not meant for support. Besides that, please make sure to follow the issue template in order to avoid your issue being closed without a solution. Thanks!
