### ISSUE TITLE
Grey Screen while opening the app

### ISSUE THREAD

**Issue by GVB1** [apache/cordova#17]
HI Team

I have created an app using Ionic3 and cordova. I see 2-3 seconds of Grey screen even before my splash screen. Need assistance in this regards on how to solve this issue.

Regards
GVB

**Comment by janpio** [comment]
Do you have the same problem with a new app created with `cordova create`?

If not, http://forum.ionicframework.com/ is probably the more appropriate location to ask.

(Just for completeness: What is your `ionic info` output?)

**Comment by raphinesse** [comment]
While I have no experience with that myself, I remember having read about a similar issue in our slack. There it was suggested that it had to do with large JavaScript bundles.

**Comment by GVB1** [comment]
> Do you have the same problem with a new app created with `cordova create`?
> 
> If not, http://forum.ionicframework.com/ is probably the more appropriate location to ask.
> 
> (Just for completeness: What is your `ionic info` output? What platform and device are you testing on?)

HI 

We are using Ionic with Cordova, and we use ::  ionic start <app-name> to create the app.

**Comment by janpio** [comment]
If the problem is not reproducible on a new Cordova only app, there is nothing we can do about it.
(You didn't answer any of the 3 questions I asked.)
