### ISSUE TITLE
Problem when running all platforms

### ISSUE THREAD

**Issue by DimitrisRK** [apache/cordova#170]
# Bug Report
Problem when running all platforms.
## Problem
When trying to run all platforms using 'cordova run' command, platforms will start running one by one. The issue is that android platform cannot locate its default target.
### What is expected to happen?
Run application in emulator or device.

### What does actually happen?
`CordovaError: Promise rejected with non-error: 'Target \'default\' not found, unable to run project'
    at cli.catch.err (C:\Users\<my_user>\AppData\Roaming\npm\node_modules\cordova\bin\cordova:29:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

## Information
Add more than 1 platforms to your Cordova project, and try running cordova run.

### Command or Code
cordova run

### Environment, Platform, Device
Android Platform.

### Version information
Windows 10, Cordova 9.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by DimitrisRK** [comment]
Looks like issue is platform-dependent.
The cause of this is run.js file of Cordova Browser platform.
For more details, see this: https://github.com/apache/cordova-browser/issues/87

**Comment by raphinesse** [comment]
Great, thanks for further investigating this. I'll go ahead and close this issue in favor of the one in `cordova-browser`
