### ISSUE TITLE
with the updated beta webview plugin can it will solve API depreciation   issue while submitting the ionic app to appstore? 

### ISSUE THREAD

**Issue by sprudhviraj** [apache/cordova#173]
When I am submitting the build it is throwing the warning message?
**Dear Developer
       Your delivery was successful, but you may wish to correct the following issues in your next delivery:ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs .**

How can we solve this issue? is there any solution for this.please provide solution or implementation as soon as possible 
Thanks 
Note: In android  there is no issue. we are facing issue  only with ios while submitting the application

**Comment by erisu** [comment]
Duplicate: https://github.com/apache/cordova-ios/issues/661
