### ISSUE TITLE
Enquiry: WKWebview in cordova iOS.

### ISSUE THREAD

**Issue by ramgrg** [apache/cordova#178]
I have an enquiry to make about WKWebview support in cordova. Since the last week of August, apple release team has started to give warning about WKWebview issue on the submitted apps. For now I am planning to use this plugin, https://github.com/apache/cordova-plugin-wkwebview-engine. But in forums, it is mentioned that, it's not that reliable. Instead to use this plugin, it will be better to wait a cordova version with WKWebview support. Is it possible to share upto when the new version with WKWebview will be released?

**Comment by jcesarmobile** [comment]
there is no date, but not sure where you have read that using the plugin is not reliable, that's not true
