### ISSUE TITLE
Implementing Google Analytics Firebase in Cordova application for Windows

### ISSUE THREAD

**Issue by ilicaleksandra** [apache/cordova#180]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Description
We implemented, sucessefully, Google analytics using firebase in iOS and Android parts of cordova project, but we are stuck with windows part of application. We used steps for creating data streams for web, on Google Analytics page.

Did anyone succeeded in implementation ? We got no errors, neither on google side nor on application side.
### Environment, Platform, Device

Cordova Windows, Google Analytics, Firebase

## Checklist

- [x] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by brodybits** [comment]
This looks like an issue with a third-party plugin. I would highly recommend you raise an issue on the third-party plugin with a [minimal, reproducible example][minimal-reproducible-example].

[minimal-reproducible-example]: https://stackoverflow.com/help/minimal-reproducible-example
