### ISSUE TITLE
Cordova connection to the server issue.

### ISSUE THREAD

**Issue by minalsavant** [apache/cordova#190]
Application Error - The connection to the server was unsuccessful. (file:///android_asset/www/index.html)

### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Checklist

- [ ] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
Apache Cordova uses GitHub Issues as a feature request and bug tracker _only_.
For usage and support questions, please check out the resources below. Thanks!

---

You can get answers to your usage and support questions about **Apache Cordova** on:

* Slack Community Chat: https://cordova.slack.com (you can sign-up at http://slack.cordova.io/)
* StackOverflow: https://stackoverflow.com/questions/tagged/cordova using the tag `cordova`


With all required information missing, it's unlikely that we would be able to help you.
