### ISSUE TITLE
Display interface with issues on some iphones.

### ISSUE THREAD

**Issue by jonnathanlopes** [apache/cordova#191]
I build an application with osen and Angular and after packing on Cordova I am having bad display problem with the following devices. In the google emulator, everything works fine, but the Xcode emulator before packing cordova presents the problem in: 
IPHONE 6 bad
IPHONE 6+ bad
IPHONE 6S bad
IPHONE 6S + bad
IPHONE 7 bad
IPHONE 7+ bad
IPHONE 8 bad
IPHONE 8 + bad
IPad bad
IPad AIR 2 bad
![bad](https://user-images.githubusercontent.com/26045692/72186091-32b41480-33d3-11ea-8317-ec5528710375.png)
In the devices below it works perfectly : 
IPHONE X OK
IPHONE XS OK
IPHONE XS MAX OK
IPHONE 11 OK
![ok](https://user-images.githubusercontent.com/26045692/72186117-40699a00-33d3-11ea-86bc-4719f08f8608.png)

**Comment by timbru31** [comment]
Looks like you need to install and configure the statusbar plugin

**Comment by jcesarmobile** [comment]
This looks like a framework problem or a viewport fit bad usage or both, not related to cordova, closing
