### ISSUE TITLE
unable to Gzip and Deflate compression in root www folder for multiple file formats

### ISSUE THREAD

**Issue by onelsonic** [apache/cordova#194]
on Apache you will setup an .htaccess file to specify the file headers and return the correct file format to the client which will decompress it.

in the .htaccess file you will specify the file type and encoding method.
Here we want to decompress html and js files from GZIP format when the client receive the files.
>>
AddType text/html .html
AddType application/javascript .js
AddEncoding gzip .html
AddEncoding gzip .js

I am unable to do the same with the current version of Cordova with the files in the root /www/

Is this a bug?

in 2015 you could use some server code in order to do so :
```
require('http').createServer(function(request, response) {
  response.writeHead(200, { 'content-encoding': 'gzip', 'content-type': 'application/gzip' });
  require('fs').createReadStream('platforms/platforms.json').pipe(require('zlib').createGzip()).pipe(response);
}).listen(1337);
```
This is not working anymore.

Can this be added/supported? Similar to what we have on Apache?
Or is there a new workaround?

If this is not making any sense to you check the below:
https://www.apphp.com/tutorials/index.php?page=gzip-and-deflate-compression-in-web-development

**Comment by breautek** [comment]
Can you tell me the point of this?

compressing files are generally only beneficial when you're sending that file through the network. The files inside your cordova `www` folder are being loaded directly from the filesystem, so no network is involved here. If anything, I think  this will result of longer loader times because it needs to compress and then decompress before the browser can start parsing.

**Comment by onelsonic** [comment]
Hi @breautek 
> we then get some faster downloads of the final app.
App size is reduced by 46% overall using Gzip/Deflate.
While tested loading times are only 10% longer so it's a win-win.

**Comment by breautek** [comment]
I see. This would require significant changes on the native side of each platform. The browser gzip functionality is part of their network stack, so it is not used when files are being loaded from the filesystem, which means each native implementation would have to include a gzip implementation and override resource loading (if that is even possible)

 I don't consider this a win-win, especially for the level of maintenance (high-risk to be app-breaking if something goes wrong) that would be required in the future.

> We should have the option to do it like in previous versions.

Cordova has never had a feature that compresses the `www` directory or any file inside that directory. It simply copies the files to the native app project that it manages for you. 

Cordova can use a remote URL as it's content loading point, and the webserver can use gzip so perhaps this is what you were thinking about, but this is **NOT** the recommended approach for final deployments, as it can be a reason for app rejection from the app stores.

Don't forget that, at least on android, APKs are already compressed (they are simply zip files afterall). I think it's safe to assume that the iOS IPA files are also compressed, though I don't know for sure.

If you want this kind of functionality, it would be better suited as a cordova plugin.

For the reasons above, I'll be closing this ticket.
