### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by eduferfer** [apache/cordova#212]
I am building a mobile app for Android using cordova and I implement an OAuth2 workflow.

When the authentication endpoint redirects back to my app, this navigation is blocked showing the following message:

**Application Error**
net::ERR_CONNECTION_REFUSED(http://localhost/home?code=<my code>)

When serving my app with livereload it works fine, probably because a port is added to the url?

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
