### ISSUE TITLE
Issue signing android debug apk

### ISSUE THREAD

**Issue by dan8551** [apache/cordova#213]
# Bug Report

## Problem
When signing an APK using cordova run android --release -- --keystore=XXX --storePassword=XXX --alias=XXX --password=XXX an APK is produced with a correctly signed APK.
When signing an APK exactly the same as above using --debug an APK is produced with a different signature.

### What is expected to happen?
Correct signature applied to APK.

### What does actually happen?
Wrong signature applied.

### Environment, Platform, Device

Windows 10 PC

### Version information

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by timbru31** [comment]
This is the wrong repo for this. cordova-android is the correct one. Also, your issue is missing required information.
