### ISSUE TITLE
executing npm install -g cordova@10.0.0 gives error

### ISSUE THREAD

**Issue by sanket-bhalerao** [apache/cordova#231]
# Bug Report

## Problem
when i try to upgrade cordova to version 10.0.0 it gives error 

`
λ npm install -g cordova@latest
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@netflix%2fnerror - Not found
npm ERR! 404
npm ERR! 404  '@netflix/nerror@^1.1.3' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'cordova-common'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
`
### What is expected to happen?

cordova global version should get upgraded/version 10.0.0 should get installed.

### What does actually happen?

![image](https://user-images.githubusercontent.com/9264813/89519120-7fd95700-d7f9-11ea-9ec7-0e38aa8d995a.png)

## Information

as suggested in[ this blog](https://cordova.apache.org/announcements/2020/08/04/cordova-cli-release-10.0.0.html) i uninstalled the cordova global version and tried to install it again with @10.0.0 when that failed i tried to install it using @latest as well. Both results in the same error.

### Command or Code

npm uninstall -g cordova -> succeeds 
npm install -g cordova@10.0.0 -> fails

### Environment, Platform, Device

Windows 10

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
Duplicate: https://github.com/apache/cordova-common/issues/149

NPM is currently having an issue. https://status.npmjs.org/

**Comment by erisu** [comment]
Sorry correction, the duplicate linked issue is not exactly a complete duplicate but the ticket contains a response to the actual  current issue you have reported here.

Link to exact reponse:
https://github.com/apache/cordova-common/issues/149#issuecomment-669816061

In the mean time, please monitor the npmjs registry status and try again after they have resolved the issue.
