### ISSUE TITLE
Phonegap push plugin deprecation

### ISSUE THREAD

**Issue by AdriVanHoudt** [apache/cordova#237]
(Let me know if I'm in the wrong place to ask)

We used https://github.com/phonegap/phonegap-plugin-push but the latest version seems to fail on latest Cordova.
It also seems that the project is archived. I have no idea why/when, I can only assume due to PhoneGap going away.
I can also not directly ask them as the repo is archived.

Is there a plan from Apache/the Cordova project to adopt the plugin? I believe it is widely used.
In the meantime I've found https://github.com/havesource/cordova-plugin-push to be a good drop in replacement/fix.

**Comment by breautek** [comment]
Adobe has officially [ended support](https://blog.phonegap.com/update-for-customers-using-phonegap-and-phonegap-build-cc701c77502c) for PhoneGap and it will on longer be maintained, hence why the phonegap repos are being archived.

There hasn't really been any discussion of adopting the push plugin, or any of the other phonegap plugins at this time. So currently https://github.com/havesource/cordova-plugin-push is the best replacement. Many of the Apache contributors are actually contributing to that project already.

> (Let me know if I'm in the wrong place to ask)

Usually we use [slack](http://slack.cordova.io/) for more support style questions.

Let me know if this answers your questions and I'll close this issue.

**Comment by AdriVanHoudt** [comment]
I figured they archived it due to the end of PhoneGap, but it isn't stated anywhere.
Usually people add a notice in the readme or something.

Slack is nice but doing it like this will hopefully allow others to find https://github.com/havesource/cordova-plugin-push as well. Since the original repo doesn't allow any issues it is nice to have somme public info out there.
