### ISSUE TITLE
Building a existing vue.js project into cordova.

### ISSUE THREAD

**Issue by SamnnyWong** [apache/cordova#247]
What I did: The vue.js project development is finished. I run `npm run build` in the vue project directory, which created a .dist directory. Then I deleted everything in the www folder, copy everything inside the .dist folder and paste everything into the www folder.

 In my cordova project directory, run `cordova run android`, no issue prompted in the terminal, the device had the apk installed, but its running with a blank white page where it supposed to run my vue.js build product.

Did I do something wrong?

**Comment by breautek** [comment]
We cannot provide much assistance without knowing all the information requested in the issue form.

Generally speaking, a white screen on launch indicates a javascript error that is occurring. Use the chrome web inspector remote tools (navigate to `chrome://inspect`) to debug the app.
