### ISSUE TITLE
This bundle is invalid. The info.plist is missing or could not be parsed when validating iOs app

### ISSUE THREAD

**Issue by mkt-van** [apache/cordova#248]
Hello, I'm trying to validate my Cordova iOs app for testflight. But I'm getting this error. 
![for skype](https://user-images.githubusercontent.com/71452555/93490077-9a473a00-f93a-11ea-935a-07f4664400f5.png)

and here is my files.
![for skype2](https://user-images.githubusercontent.com/71452555/93490903-a67fc700-f93b-11ea-8dd9-16802a032e49.png)

I can't see that Info.plist file on my directory, but I can see another .plist file which is travelon-info.plist under Resources folder.
I tried renaming it but still doesn't work. I'm new to swift and even MacOsX, hopefully someone could shed some light. Thank you so much in advance.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).

**Comment by mkt-van** [comment]
Thank you for your response @timbru31, incase someone will also be reading this. I was just an invalid character on my .plist file that can be seen using vi text editor or others.
