### ISSUE TITLE
npm uninstall -g cordova npm install -g cordova@10.0.0 not working crash I need update name="android-targetSdkVersion" value="29" Android 10

### ISSUE THREAD

**Issue by MobileAsociart** [apache/cordova#251]
# Bug Report

## Problem

npm uninstall -g cordova npm install -g cordova@10.0.0 not working crash I need update name="android-targetSdkVersion" value="29" Android 10

### Command or Code

npm uninstall -g cordova npm install -g cordova@10.0.0 

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
> not working crash

Please provide the actual crash details... stack traces, error messages, etc.

**Comment by MobileAsociart** [comment]
E:\Install>cordova -v
C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\update-notifier\index.js:103
        async fetchInfo() {
              ^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\cordova\src\cli.js:19:22)




E:\Install>npm install -g cordova > log.txt
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported


C:\Users\user\AppData\Roaming\npm\cordova -> C:\Users\user\AppData\Roaming\npm\node_modules\cordova\bin\cordova
- @types/minimatch@3.0.3 node_modules\cordova\node_modules\@types\minimatch
- @types/node@14.14.2 node_modules\cordova\node_modules\@types\node
- @types/glob@7.1.3 node_modules\cordova\node_modules\@types\glob
- arr-diff@4.0.0 node_modules\cordova\node_modules\arr-diff
- arr-flatten@1.1.0 node_modules\cordova\node_modules\arr-flatten
- arr-union@3.1.0 node_modules\cordova\node_modules\arr-union
- array-uniq@1.0.3 node_modules\cordova\node_modules\array-uniq
- array-unique@0.3.2 node_modules\cordova\node_modules\array-unique
- assign-symbols@1.0.0 node_modules\cordova\node_modules\assign-symbols
- atob@2.1.2 node_modules\cordova\node_modules\atob
- call-me-maybe@1.0.1 node_modules\cordova\node_modules\call-me-maybe
- capture-stack-trace@1.0.1 node_modules\cordova\node_modules\capture-stack-trace
- component-emitter@1.3.0 node_modules\cordova\node_modules\component-emitter
- copy-descriptor@0.1.1 node_modules\cordova\node_modules\copy-descriptor
- fs-extra@7.0.1 node_modules\cordova\node_modules\cordova-create\node_modules\fs-extra
- fs-extra@7.0.1 node_modules\cordova\node_modules\cordova-fetch\node_modules\fs-extra
- fs-extra@7.0.1 node_modules\cordova\node_modules\cordova-lib\node_modules\fs-extra
- create-error-class@3.0.2 node_modules\cordova\node_modules\create-error-class
- decode-uri-component@0.2.0 node_modules\cordova\node_modules\decode-uri-component
- for-in@1.0.2 node_modules\cordova\node_modules\for-in
- get-value@2.0.6 node_modules\cordova\node_modules\get-value
- is-glob@3.1.0 node_modules\cordova\node_modules\glob-parent\node_modules\is-glob
- glob-to-regexp@0.3.0 node_modules\cordova\node_modules\glob-to-regexp
- @mrmlnc/readdir-enhanced@2.2.1 node_modules\cordova\node_modules\@mrmlnc\readdir-enhanced
- pify@4.0.1 node_modules\cordova\node_modules\globby\node_modules\pify
- indent-string@3.2.0 node_modules\cordova\node_modules\indent-string
- is-buffer@1.1.6 node_modules\cordova\node_modules\is-buffer
- kind-of@4.0.0 node_modules\cordova\node_modules\has-values\node_modules\kind-of
- has-values@1.0.0 node_modules\cordova\node_modules\has-values
- has-value@1.0.0 node_modules\cordova\node_modules\has-value
- kind-of@3.2.2 node_modules\cordova\node_modules\is-accessor-descriptor\node_modules\kind-of
- is-accessor-descriptor@0.1.6 node_modules\cordova\node_modules\is-accessor-descriptor
- kind-of@3.2.2 node_modules\cordova\node_modules\is-data-descriptor\node_modules\kind-of
- is-data-descriptor@0.1.4 node_modules\cordova\node_modules\is-data-descriptor
- kind-of@5.1.0 node_modules\cordova\node_modules\is-descriptor\node_modules\kind-of
- is-descriptor@0.1.6 node_modules\cordova\node_modules\is-descriptor
- define-property@0.2.5 node_modules\cordova\node_modules\class-utils\node_modules\define-property
- define-property@0.2.5 node_modules\cordova\node_modules\expand-brackets\node_modules\define-property
- is-extendable@0.1.1 node_modules\cordova\node_modules\is-extendable
- extend-shallow@2.0.1 node_modules\cordova\node_modules\braces\node_modules\extend-shallow
- extend-shallow@2.0.1 node_modules\cordova\node_modules\expand-brackets\node_modules\extend-shallow
- extend-shallow@2.0.1 node_modules\cordova\node_modules\extglob\node_modules\extend-shallow
- extend-shallow@2.0.1 node_modules\cordova\node_modules\fill-range\node_modules\extend-shallow
- kind-of@3.2.2 node_modules\cordova\node_modules\is-number\node_modules\kind-of
- is-plain-object@2.0.4 node_modules\cordova\node_modules\is-plain-object
- is-extendable@1.0.1 node_modules\cordova\node_modules\extend-shallow\node_modules\is-extendable
- extend-shallow@3.0.2 node_modules\cordova\node_modules\extend-shallow
- is-redirect@1.0.0 node_modules\cordova\node_modules\is-redirect
- is-retry-allowed@1.2.0 node_modules\cordova\node_modules\is-retry-allowed
- is-url@1.2.4 node_modules\cordova\node_modules\is-url
- is-windows@1.0.2 node_modules\cordova\node_modules\is-windows
- isarray@1.0.0 node_modules\cordova\node_modules\isarray
- kind-of@6.0.3 node_modules\cordova\node_modules\kind-of
- is-accessor-descriptor@1.0.0 node_modules\cordova\node_modules\base\node_modules\is-accessor-descriptor
- is-data-descriptor@1.0.0 node_modules\cordova\node_modules\base\node_modules\is-data-descriptor
- is-descriptor@1.0.2 node_modules\cordova\node_modules\base\node_modules\is-descriptor
- define-property@1.0.0 node_modules\cordova\node_modules\base\node_modules\define-property
- is-accessor-descriptor@1.0.0 node_modules\cordova\node_modules\define-property\node_modules\is-accessor-descriptor
- is-data-descriptor@1.0.0 node_modules\cordova\node_modules\define-property\node_modules\is-data-descriptor
- is-descriptor@1.0.2 node_modules\cordova\node_modules\define-property\node_modules\is-descriptor
- define-property@2.0.2 node_modules\cordova\node_modules\define-property
- is-accessor-descriptor@1.0.0 node_modules\cordova\node_modules\extglob\node_modules\is-accessor-descriptor
- is-data-descriptor@1.0.0 node_modules\cordova\node_modules\extglob\node_modules\is-data-descriptor
- is-descriptor@1.0.2 node_modules\cordova\node_modules\extglob\node_modules\is-descriptor
- define-property@1.0.0 node_modules\cordova\node_modules\extglob\node_modules\define-property
- map-cache@0.2.2 node_modules\cordova\node_modules\map-cache
- fragment-cache@0.2.1 node_modules\cordova\node_modules\fragment-cache
- is-extendable@1.0.1 node_modules\cordova\node_modules\mixin-deep\node_modules\is-extendable
- mixin-deep@1.3.2 node_modules\cordova\node_modules\mixin-deep
- define-property@0.2.5 node_modules\cordova\node_modules\object-copy\node_modules\define-property
- kind-of@3.2.2 node_modules\cordova\node_modules\object-copy\node_modules\kind-of
- object-copy@0.1.0 node_modules\cordova\node_modules\object-copy
- object-visit@1.0.1 node_modules\cordova\node_modules\object-visit
- map-visit@1.0.0 node_modules\cordova\node_modules\map-visit
- collection-visit@1.0.0 node_modules\cordova\node_modules\collection-visit
- object.pick@1.3.0 node_modules\cordova\node_modules\object.pick
- opn@5.5.0 node_modules\cordova\node_modules\opn
- pascalcase@0.1.1 node_modules\cordova\node_modules\pascalcase
- path-dirname@1.0.2 node_modules\cordova\node_modules\path-dirname
- posix-character-classes@0.1.1 node_modules\cordova\node_modules\posix-character-classes
- pseudomap@1.0.2 node_modules\cordova\node_modules\pseudomap
- pify@4.0.1 node_modules\cordova\node_modules\read-chunk\node_modules\pify
- repeat-element@1.1.3 node_modules\cordova\node_modules\repeat-element
- repeat-string@1.6.1 node_modules\cordova\node_modules\repeat-string
- resolve-url@0.2.1 node_modules\cordova\node_modules\resolve-url
- ret@0.1.15 node_modules\cordova\node_modules\ret
- safe-regex@1.1.0 node_modules\cordova\node_modules\safe-regex
- regex-not@1.0.2 node_modules\cordova\node_modules\regex-not
- extend-shallow@2.0.1 node_modules\cordova\node_modules\set-value\node_modules\extend-shallow
- is-accessor-descriptor@1.0.0 node_modules\cordova\node_modules\snapdragon-node\node_modules\is-accessor-descriptor
- is-data-descriptor@1.0.0 node_modules\cordova\node_modules\snapdragon-node\node_modules\is-data-descriptor
- is-descriptor@1.0.2 node_modules\cordova\node_modules\snapdragon-node\node_modules\is-descriptor
- define-property@1.0.0 node_modules\cordova\node_modules\snapdragon-node\node_modules\define-property
- kind-of@3.2.2 node_modules\cordova\node_modules\snapdragon-util\node_modules\kind-of
- snapdragon-util@3.0.1 node_modules\cordova\node_modules\snapdragon-util
- snapdragon-node@2.1.1 node_modules\cordova\node_modules\snapdragon-node
- define-property@0.2.5 node_modules\cordova\node_modules\snapdragon\node_modules\define-property
- extend-shallow@2.0.1 node_modules\cordova\node_modules\snapdragon\node_modules\extend-shallow
- source-map@0.5.7 node_modules\cordova\node_modules\source-map
- source-map-url@0.4.0 node_modules\cordova\node_modules\source-map-url
- split-string@3.1.0 node_modules\cordova\node_modules\split-string
- set-value@2.0.1 node_modules\cordova\node_modules\set-value
- define-property@0.2.5 node_modules\cordova\node_modules\static-extend\node_modules\define-property
- static-extend@0.1.2 node_modules\cordova\node_modules\static-extend
- class-utils@0.3.6 node_modules\cordova\node_modules\class-utils
- cross-spawn@5.1.0 node_modules\cordova\node_modules\term-size\node_modules\cross-spawn
- get-stream@3.0.0 node_modules\cordova\node_modules\term-size\node_modules\get-stream
- execa@0.7.0 node_modules\cordova\node_modules\term-size\node_modules\execa
- timed-out@4.0.1 node_modules\cordova\node_modules\timed-out
- kind-of@3.2.2 node_modules\cordova\node_modules\to-object-path\node_modules\kind-of
- to-object-path@0.3.0 node_modules\cordova\node_modules\to-object-path
- to-regex@3.0.2 node_modules\cordova\node_modules\to-regex
- union-value@1.0.1 node_modules\cordova\node_modules\union-value
- isobject@2.1.0 node_modules\cordova\node_modules\unset-value\node_modules\has-value\node_modules\isobject
- has-values@0.1.4 node_modules\cordova\node_modules\unset-value\node_modules\has-values
- has-value@0.3.1 node_modules\cordova\node_modules\unset-value\node_modules\has-value
- unset-value@1.0.0 node_modules\cordova\node_modules\unset-value
- cache-base@1.0.1 node_modules\cordova\node_modules\cache-base
- base@0.11.2 node_modules\cordova\node_modules\base
- unzip-response@2.0.1 node_modules\cordova\node_modules\unzip-response
- configstore@3.1.5 node_modules\cordova\node_modules\update-notifier\node_modules\configstore
- urix@0.1.0 node_modules\cordova\node_modules\urix
- source-map-resolve@0.5.3 node_modules\cordova\node_modules\source-map-resolve
- use@3.1.1 node_modules\cordova\node_modules\use
- snapdragon@0.8.2 node_modules\cordova\node_modules\snapdragon
- expand-brackets@2.1.4 node_modules\cordova\node_modules\expand-brackets
- extglob@2.0.4 node_modules\cordova\node_modules\extglob
- nanomatch@1.2.13 node_modules\cordova\node_modules\nanomatch
- pify@4.0.1 node_modules\cordova\node_modules\with-open-file\node_modules\pify
C:\Users\user\AppData\Roaming\npm
`-- cordova@10.0.0 
  +-- configstore@5.0.1 
  | +-- dot-prop@5.3.0 
  | | `-- is-obj@2.0.0 
  | +-- make-dir@3.1.0 
  | | `-- semver@6.3.0 
  | +-- unique-string@2.0.0 
  | | `-- crypto-random-string@2.0.0 
  | +-- write-file-atomic@3.0.3 
  | | `-- typedarray-to-buffer@3.1.5 
  | `-- xdg-basedir@4.0.0 
  +-- cordova-common@4.0.2 
  | +-- @netflix/nerror@1.1.3 
  | | `-- extsprintf@1.4.0 
  | +-- bplist-parser@0.2.0 
  | +-- cross-spawn@7.0.3 
  | | +-- path-key@3.1.1 
  | | +-- shebang-command@2.0.0 
  | | | `-- shebang-regex@3.0.0 
  | | `-- which@2.0.2 
  | +-- fast-glob@3.2.4 
  | | +-- @nodelib/fs.stat@2.0.3 
  | | +-- @nodelib/fs.walk@1.2.4 
  | | | +-- @nodelib/fs.scandir@2.1.3 
  | | | | `-- run-parallel@1.1.10 
  | | | `-- fastq@1.8.0 
  | | |   `-- reusify@1.0.4 
  | | +-- glob-parent@5.1.1 
  | | +-- micromatch@4.0.2 
  | | | `-- braces@3.0.2 
  | | |   `-- fill-range@7.0.1 
  | | |     `-- to-regex-range@5.0.1 
  | | |       `-- is-number@7.0.0 
  | | `-- picomatch@2.2.2 
  | +-- read-chunk@3.2.0
  | | `-- pify@4.0.1 
  | `-- strip-bom@4.0.0 
  +-- cordova-create@3.0.0 
  | +-- cordova-app-hello-world@5.0.0 
  | +-- cordova-fetch@3.0.0 
  | | `-- pify@5.0.0 
  | +-- globby@11.0.1 
  | | +-- array-union@2.1.0 
  | | +-- dir-glob@3.0.1 
  | | | `-- path-type@4.0.0 
  | | +-- ignore@5.1.8 
  | | `-- slash@3.0.0 
  | +-- isobject@4.0.0 
  | +-- npm-package-arg@8.1.0 
  | | `-- hosted-git-info@3.0.7 
  | |   `-- lru-cache@6.0.0 
  | |     `-- yallist@4.0.0 
  | `-- tmp@0.2.1 
  |   `-- rimraf@3.0.2 
  +-- cordova-lib@10.0.0 
  | +-- cordova-serve@4.0.0 
  | | `-- open@7.3.0 
  | |   +-- is-docker@2.1.1 
  | |   `-- is-wsl@2.2.0 
  | +-- detect-indent@6.0.0 
  | +-- detect-newline@3.1.0 
  | +-- init-package-json@1.10.3
  | | +-- npm-package-arg@6.1.1 
  | | | `-- hosted-git-info@2.8.8 
  | | +-- read-package-json@2.1.2
  | | | `-- normalize-package-data@2.5.0
  | | |   +-- hosted-git-info@2.8.8 
  | | |   `-- semver@5.7.1 
  | | `-- semver@5.7.1 
  | +-- md5-file@5.0.0 
  | +-- pify@5.0.0 
  | `-- stringify-package@1.0.1 
  +-- execa@4.0.3 
  | +-- get-stream@5.2.0 
  | +-- human-signals@1.1.1 
  | +-- is-stream@2.0.0 
  | +-- merge-stream@2.0.0 
  | +-- npm-run-path@4.0.1 
  | +-- onetime@5.1.2 
  | | `-- mimic-fn@2.1.0 
  | `-- strip-final-newline@2.0.0 
  +-- fs-extra@9.0.1 
  | +-- at-least-node@1.0.0 
  | +-- jsonfile@6.0.1 
  | `-- universalify@1.0.0 
  +-- insight@0.10.3
  | +-- chalk@2.4.2 
  | | +-- ansi-styles@3.2.1 
  | | | `-- color-convert@1.9.3 
  | | |   `-- color-name@1.1.3 
  | | `-- supports-color@5.5.0 
  | |   `-- has-flag@3.0.0 
  | +-- conf@1.4.0
  | | +-- dot-prop@4.2.1 
  | | | `-- is-obj@1.0.1 
  | | +-- make-dir@1.3.0 
  | | | `-- pify@3.0.0 
  | | `-- write-file-atomic@2.4.3 
  | +-- inquirer@6.5.2
  | | +-- chalk@2.4.2 
  | | | +-- ansi-styles@3.2.1 
  | | | | `-- color-convert@1.9.3 
  | | | |   `-- color-name@1.1.3 
  | | | `-- supports-color@5.5.0 
  | | |   `-- has-flag@3.0.0 
  | | +-- cli-cursor@2.1.0
  | | | `-- restore-cursor@2.0.0
  | | |   `-- onetime@2.0.1 
  | | |     `-- mimic-fn@1.2.0 
  | | `-- external-editor@3.1.0
  | |   `-- tmp@0.0.33 
  | +-- os-name@3.1.0
  | | `-- windows-release@3.3.3
  | |   `-- execa@1.0.0 
  | |     +-- cross-spawn@6.0.5 
  | |     | +-- path-key@2.0.1 
  | |     | +-- semver@5.7.1 
  | |     | +-- shebang-command@1.2.0 
  | |     | | `-- shebang-regex@1.0.0 
  | |     | `-- which@1.3.1 
  | |     +-- get-stream@4.1.0 
  | |     +-- is-stream@1.1.0 
  | |     `-- npm-run-path@2.0.2 
  | `-- request@2.88.2
  |   `-- http-signature@1.2.0
  |     `-- jsprim@1.4.1
  |       `-- extsprintf@1.3.0 
  +-- semver@7.3.2 
  +-- systeminformation@4.27.11 
  `-- update-notifier@4.1.3 
    +-- boxen@4.2.0 
    | +-- ansi-align@3.0.0 
    | | `-- string-width@3.1.0 
    | |   `-- emoji-regex@7.0.3 
    | +-- camelcase@5.3.1 
    | +-- cli-boxes@2.2.1 
    | +-- string-width@4.2.0 
    | | +-- emoji-regex@8.0.0 
    | | +-- is-fullwidth-code-point@3.0.0 
    | | `-- strip-ansi@6.0.0 
    | |   `-- ansi-regex@5.0.0 
    | +-- term-size@2.2.1 
    | +-- type-fest@0.8.1 
    | `-- widest-line@3.1.0 
    |   `-- string-width@4.2.0 
    |     +-- emoji-regex@8.0.0 
    |     +-- is-fullwidth-code-point@3.0.0 
    |     `-- strip-ansi@6.0.0 
    |       `-- ansi-regex@5.0.0 
    +-- chalk@3.0.0 
    | +-- ansi-styles@4.3.0 
    | | `-- color-convert@2.0.1 
    | |   `-- color-name@1.1.4 
    | `-- supports-color@7.2.0 
    |   `-- has-flag@4.0.0 
    +-- has-yarn@2.1.0 
    +-- is-ci@2.0.0 
    | `-- ci-info@2.0.0 
    +-- is-installed-globally@0.3.2 
    | +-- global-dirs@2.0.1 
    | `-- is-path-inside@3.0.2 
    +-- is-npm@4.0.0 
    +-- is-yarn-global@0.3.0 
    +-- latest-version@5.1.0 
    | `-- package-json@6.5.0 
    |   +-- got@9.6.0 
    |   | +-- @sindresorhus/is@0.14.0 
    |   | +-- @szmarczak/http-timer@1.1.2 
    |   | | `-- defer-to-connect@1.1.3 
    |   | +-- cacheable-request@6.1.0 
    |   | | +-- clone-response@1.0.2 
    |   | | +-- http-cache-semantics@4.1.0 
    |   | | +-- keyv@3.1.0 
    |   | | | `-- json-buffer@3.0.0 
    |   | | +-- lowercase-keys@2.0.0 
    |   | | +-- normalize-url@4.5.0 
    |   | | `-- responselike@1.0.2 
    |   | +-- decompress-response@3.3.0 
    |   | +-- get-stream@4.1.0 
    |   | +-- mimic-response@1.0.1 
    |   | +-- p-cancelable@1.1.0 
    |   | +-- to-readable-stream@1.0.0 
    |   | `-- url-parse-lax@3.0.0 
    |   |   `-- prepend-http@2.0.0 
    |   +-- registry-auth-token@4.2.0 
    |   +-- registry-url@5.1.0 
    |   `-- semver@6.3.0 
    +-- pupa@2.1.1 
    | `-- escape-goat@2.1.1 
    `-- semver-diff@3.1.1 
      `-- semver@6.3.0 


https://github.com/apache/cordova-android/issues/830

**Comment by timbru31** [comment]
What are your Node.js (`node -v`)and npm (`npm -v`) versions?

**Comment by MobileAsociart** [comment]
E:\Install>node -v
v6.16.0

What will be the stable and correct NodeJs version for Android 10 to work ?!

**Comment by timbru31** [comment]
Please see https://cordova.apache.org/announcements/2020/08/04/cordova-cli-release-10.0.0.html - you will need a minimum of Node.js v10.10. Your version is EOL since April 2019.
