### ISSUE TITLE
Not able to see any results in google analytics console

### ISSUE THREAD

**Issue by manivacube** [apache/cordova#254]
When we tried to add this plugin with cordova mobile apps(both ios & android), we are not able to see any results. We are not sure whether it is working properly or not. Actually we are not clear with the steps for the integration. Could you people please provide step by step guide(both analytics project setup & plugin integration) to integrate this with our app.

Dev details:-

Added plugin like below
Screenshot 2020-10-28 at 5 14 04 PM

Initiated in the ondevice ready event like below
window.ga.startTrackerWithId('UA-XXXX-XX', 30);

Tracked view details like below
window.ga.trackView(${window.device.platform} : Mobile App Login Screen);

FYI, I have raised the same with respective plugin community. Here is the link to track the issue
https://github.com/danwilson/google-analytics-plugin/issues/585

**Comment by timbru31** [comment]
I'm closing this issue since we can't support any third party plugins from the community. You should ask the author(s) of the mentioned plugin for installation instructions.
