### ISSUE TITLE
Error  while checking system requirements

### ISSUE THREAD

**Issue by spandey1296** [apache/cordova#259]
I have already installed all plugins as well as SDK and Gradle but still, I am getting errors.
Android SDK: not installed 
Failed to find the 'ANDROID_SDK_ROOT' environment variable. Try setting it manually.
Failed to find 'android' command in your 'PATH'. Try to update your 'PATH' to include path to valid SDK directory.
Android target: not installed 
Command failed with ENOENT: android list target
spawn android ENOENT

**Comment by breautek** [comment]
You're environment doesn't appear to be setup correctly.

You need to set the `ANDROID_SDK_ROOT` system variable to the path of where the android sdk directory. Additionally, the android sdk executables doesn't appear to be in your `PATH` variable.

Please see the [Android Guide](https://cordova.apache.org/docs/en/dev/guide/platforms/android/index.html) to learn how to configure your environment.

With the information provided, that's the best answer we can give. If you need further assistance, I invite you to our [slack](http://slack.cordova.io/). If you think you've found a bug, please open a new issue with the entire issue form filled out.

Thank you.
