### ISSUE TITLE
cordova platform add - failing with "failed to fetch platform" error

### ISSUE THREAD

**Issue by danjones-infinityworks** [apache/cordova#261]
# Bug Report

## Problem
Since 26th Nov at about 13:40 GMT, whenever I try to add a platform (ios or android) using `cordova platforms add` I receive an error and am unable to install the platform.

This issue seems to have been raised for ionic since near the same time yesterday https://github.com/ionic-team/ionic-cli/issues/4615

### What is expected to happen?
iOS / Android platform added to project

### What does actually happen?

Exception is shown

**iOS**
Using cordova-fetch for cordova-ios@^6.1.0
Failed to fetch platform cordova-ios@^6.1.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
CordovaError: TypeError: Cannot assign to read only property 'valueOf' of object

**Android**
Using cordova-fetch for cordova-android@^9.0.0
Failed to fetch platform cordova-android@^9.0.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
CordovaError: TypeError: Cannot assign to read only property 'valueOf' of object

## Information

Issue started to occur yesterday during build automation in Azure Pipelines, I notices npm versions were different, as it still worked locally, but maybe this was cached, as I updated to the same version locally and it started failing, but when I reverted back, it has been failing ever since.

### Command or Code
Issue can be reproduced from new project
```
cordova create hello com.example.hello HelloWorld
cd hello
cordova platform add ios
```

### Environment, Platform, Device
Tested with multiple macOS

macOS - Big Sur 11.0.1 (local machine)
macOS - Catalina 10.15 (Azure Pipelines Agent)

### Version information
Cordova CLI: 10.0.0
npm: 6.14.8

macOS - Big Sur 11.0.1 (local machine)
macOS - Catalina 10.15 (Azure Pipelines Agent)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by danjones-infinityworks** [comment]
Fixed is other issue

**Comment by ath0mas** [comment]
Hi, can you retry now?
I also had kind of severe "corruptions" of npm packages yesterday, _require_ instructions resulting in _TypeError_, while building cordova app too but not precisely with cordova packages... really strange
