### ISSUE TITLE
No support for NodeJS 15

### ISSUE THREAD

**Issue by LoranRendel** [apache/cordova#262]
```
cordova platform add browser
Using cordova-fetch for cordova-browser@^6.0.0
Failed to fetch platform cordova-browser@^6.0.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
CordovaError: CordovaError: Could not determine package name from output:
added 114 packages, and audited 114 packages in 5s
```

```
cordova -v
10.0.0
```

```
node -v
v15.3.0
```

```
npm -v
7.0.14
```

**Comment by breautek** [comment]
Cordova doesn't support NPM 7 (yet). See https://github.com/apache/cordova-lib/issues/859 for details/tracking.

It's recommended to use LTS versions of Node (their even versions, e.g: Node 10 / 12 / 14). Cordova doesn't officially support Node bleeding edge (their short term support odd versions, e.g: 11 / 13 / 15).

Nonetheless, NodeJS 15 will _probably_ still work fine as long as you downgrade NPM back to 6.x. You can do this by doing `npm install -g npm@6`.

Closing this issue as a duplicate.
