### ISSUE TITLE
"TypeError: Failed to fetch" - Only on using fetch method on Android

### ISSUE THREAD

**Issue by BenTimor** [apache/cordova#267]
# Support / Bug Report

## Problem

I have an express server which has an API endpoint of /todo/set which gets a JSON, POST request. This API uses cors.

The API's working, it's tested with Postman (On same computer and on another computer on same LAN) and it's working with fetch (JavaScript) when using a browser (both on phone and computer). Tried to check it both with only running Svelte server and using cordova browser platform.

The problem is, When using Cordova android application, the fetch is returning "TypeError: Failed to fetch" and the server is not getting the request.

This is the code for example:
```
fetch(`http://localhost:8080/todo/set`, {
    method: "post",
    body: JSON.stringify({
        'Text': 'Test!'
    }),
    headers: {
        'Content-Type': 'application/json',
    }
}).then(res => alert(res)).catch(err => alert(err))
```

* Tried to replace the "localhost" with my local IP. Same issue. 
* The code is the same for the phone application and the website, I'm just running it differently (`cordova run android` vs `cordova run browser`).

### What is expected to happen?
The server had to get the request at least.

### What does actually happen?
Throwing an error and the server is not getting any request.

## Information
Posted it also on StackOverflow, Maybe it's a little more clear there: https://stackoverflow.com/questions/65864040/typeerror-failed-to-fetch-only-on-cordova-application

### Reproduce
- Create a local express server and try to fetch json data from it via Cordova android applicatoin. 

### Environment, Platform, Device
- Developing on Arch Linux.
- The application is for android phone, Samsung Note 9 specifically

### Version information
- Using Svelte for Frontend 3.0.0
- Cordova 10.0.0
- Cordova platform LS:
```
Installed platforms:
  android 9.0.0
  browser
```
I'm using a clone of this repository for the application development: https://github.com/BenTimor/SvelteCordova

## Checklist
- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by breautek** [comment]
If you're testing on a physical device, then `localhost` is not going to work, as that refers to the local device  (aka the phone itself), which I assume the server isn't running on.

You need to make sure the following:
- the server is bound to a reachable ip address. For simplicity, the server can listen on 0.0.0.0, which means use any available ip address.
- the server and the device should be connected to the same network. If you're on a home network, then your ip address will probably look like 192.168.x.y. `x` will be the same for your phone and the server, but `y` will be different.
- finally, in your app, you should be referencing the server ip address, not localhost or 127.0.0.1.

To determine the ip address on the server use `ipconfig` on windows, or `ifconfig` on linux/mac.

On the phone, you can see the ip address by viewing your wifi connection details. ( Settings > wifi > your connected wifi)

![Screenshot_20210124-094345_Settings](https://user-images.githubusercontent.com/11200662/105632098-fa3d7800-5e27-11eb-82c3-03d72105ef18.jpg)

Let me know if this helps.

**Comment by BenTimor** [comment]
> If you're testing on a physical device, then `localhost` is not going to work, as that refers to the local device (aka the phone itself), which I assume the server isn't running on.
> 
> You need to make sure the following:
> 
> * the server is bound to a reachable ip address. For simplicity, the server can listen on 0.0.0.0, which means use any available ip address.
> * the server and the device should be connected to the same network. If you're on a home network, then your ip address will probably look like 192.168.x.y. `x` will be the same for your phone and the server, but `y` will be different.
> * finally, in your app, you should be referencing the server ip address, not localhost or 127.0.0.1.
> 
> To determine the ip address on the server use `ipconfig` on windows, or `ifconfig` on linux/mac.
> 
> Let me know if this helps.

Sorry if the post wasn't clear, I know what you're talking about and I've already tried it all.

I've even installed an application named "Restler" which is very similar to Postman and it's working to send the request to the server (from my phone!), But my application doesn't send any request.

Even if I'm hosting the application as a static (only frontend) website and using it on my phone it keeps working. It's only not working as an APK (And ofcourse I'm not changing the code, Only compiling it with Cordova).

**Comment by breautek** [comment]
Ok, we will need to know the exact error message you are seeing to provide anymore insight.

**Comment by BenTimor** [comment]
> Ok, we will need to know the exact error message you are seeing to provide anymore insight.

This is all I get on the alert:
![image](https://user-images.githubusercontent.com/11685140/105633814-7f924e00-5e63-11eb-995d-974593f9e8ff.png)

**Comment by breautek** [comment]
Use the chrome web inspector to remote debug your application. This will give you much more information about what's going on.

**Comment by BenTimor** [comment]
I solved it! This was the solution: https://stackoverflow.com/questions/59116787/failed-to-load-resource-neterr-cleartext-not-permitted

Thank you for your help @breautek !
