### ISSUE TITLE
Documentation Google Play Services missing ?

### ISSUE THREAD

**Issue by FloodGames** [apache/cordova#268]
Isn't it pretty basic to automatically login to your google account in the android version? I tried my hardest but could not find any relevant documentation on this matter. 

![image](https://user-images.githubusercontent.com/60991890/106486375-de824380-64b1-11eb-812d-7bf85007fce3.png)
source: https://developers.google.com/games/services/android/quickstart#step_3_modify_your_code

I have added to config.xml :
`<preference name="GradlePluginGoogleServicesEnabled" value="true" />`

I uploaded a google-services.json file to 
`\platforms\android\app`

End result should be something like this, right? Unfortunately, it's not spawning
![image](https://user-images.githubusercontent.com/60991890/106487492-ff976400-64b2-11eb-9d0d-212afc9554df.png)

I found out that the ids.xml mentioned by google is not even being created. Do I need to 'hook' these files after creation?

**Comment by breautek** [comment]
Duplicate: https://github.com/apache/cordova-android/issues/1159
