### ISSUE TITLE
globalThis is not defined

### ISSUE THREAD

**Issue by ckolobov** [apache/cordova#276]
# Bug Report

## Problem
I use Node 11.10.1 and Cordova 9.0.0

When I run
```
cordova platform add ios@6.1.1
```
the result is:
```
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: io.cordova.hellocordova
	Name: HelloCordova
iOS project created with cordova-ios@6.1.1
globalThis is not defined
(node:88875) ExperimentalWarning: queueMicrotask() is experimental.
```

And after
```
cordova run ios
```
the result is:
```
globalThis is not defined
(node:1185) ExperimentalWarning: queueMicrotask() is experimental.
```

### What is expected to happen?
successful run 

### What does actually happen?
```
globalThis is not defined
```

## Information

The problem is reproduced only with Node 11
I found module queue-microtask@1.2.2 that has issue with node v11: https://github.com/feross/queue-microtask/issues/17

Dependencies from cordova-ios@6.1.1 to queue-microtask@1.2.2
cordova-ios@6.1.1
cordova-common@4.0.2
fast-glob@3.2.5
@nodelib/fs.walk@1.2.6
@nodelib/fs.scandir@2.1.4
run-parallel@1.2.0
queue-microtask@1.2.2

### Command or Code

```
npm install -g cordova@9.0.0
```
Then in your app:
```
cordova platform add ios@6.1.1
cordova run ios
```

### Environment, Platform, Device

MacBook

### Version information

node -v //11.10.1
cordova -v //9.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
Duplicate: https://github.com/apache/cordova-android/issues/1162
