### ISSUE TITLE
Unrecognized option: --illegal-access=permit

### ISSUE THREAD

**Issue by davidhealey** [apache/cordova#285]
When adding the Android platform it creates _gradlew_ file which is add "--illegal-access=permit" to the java arguments. This isn't valid for JDK-8 and so causes an error when trying to build.

**Comment by breautek** [comment]
`cordova-android` does not add this to the `gradlew` file.

I assume it must be coming from a plugin, I would advise doing a search in your `plugins/` folder to see which plugin may be adding this.

I'll be closing this issue, but if you believe there is an actual bug with the android platform, I'd suggest opening a new issue in the [cordova-android](https://github.com/apache/cordova-android/issues) repository. Please pay attention to the form provided and fill out everything that is asked to avoid delays.

If you require more support, then I'll invite you to our [Slack](http://slack.cordova.io/) community.

Kind regards,
Norman
