### ISSUE TITLE
Remove docs translations

### ISSUE THREAD

**Issue by janpio** [apache/cordova#29]
- [ ] cordova-docs (https://github.com/apache/cordova-docs/issues/995)
- [x] plugin READMEs
- [x] other?

**Comment by raphinesse** [comment]
+1 from me, as the translations are not really maintainable.

**Comment by raphinesse** [comment]
Do we have translations anywhere else than in docs? If not, then this can be closed IMO.

**Comment by timbru31** [comment]
Some plugins had a docs folder but I think we already removed them all.

**Comment by raphinesse** [comment]
Thanks for the info. I checked and could find no remaining translations other than in cordova-docs. I'll close this issue as docs has its own.
