### ISSUE TITLE
Installed Build Tools revision 31.0.0 is corrupted. Remove and install again using the SDK Manager.

### ISSUE THREAD

**Issue by chapuawe2** [apache/cordova#296]
# Bug Report

### What is expected to happen?

I ran `cordova build android` on my Windows with Android Studio SDK

### What does actually happen?

and got this error:
`Installed Build Tools revision 31.0.0 is corrupted. Remove and install again using the SDK Manager.`

## Information

Newly installed Android Studio with SDK 31.0.0

### Command or Code

`cordova build android` on a new app builded with cordova

### Environment, Platform, Device

Windows

### Version information

Cordova CLI

## Checklist

- [ x ] I searched for existing GitHub issues
- [ x ] I updated all Cordova tooling to most recent version
- [ x ] I included all the necessary information above

## Solution

By https://stackoverflow.com/a/68430992

First of all, I face this issue in Android Studio 4.2.2 and you not need to downgrade the SDK build tool 31 to 30 or not to change compile SDK version.

The main problem is the two files missing in SDK build tool 31 that are

    dx.bat
    dx.jar

The solution is that these files are named d8 in the file location so changing their name to dx will solve the error.

The steps are below.

    go to the location

     "C:\Users\user\AppData\Local\Android\Sdk\build-tools\31.0.0"

    find a file named d8.bat. This is a Windows batch file.

    rename d8.bat to dx.bat.

    after changing d8.jar to dx.jar // now rename d8.jar to dx.jar

    It will be in location:

     "C:\Users\user\AppData\Local\Android\Sdk\build-tools\31.0.0\lib"

    Remember AppData is a hidden folder. Turn on hidden items to see the AppData folder.

Now run your project...

**Comment by breautek** [comment]
Cordova doesn't support build tools 31, and cannot do so without implementing breaking changes.

It requires AGP 7 and Java 11 for it to work properly. 

I also would advise against changing build tools, dx is intentionally missing because Google is replacing it with a different tool.
