### ISSUE TITLE
Define how Cordova handles `package-lock.json`

### ISSUE THREAD

**Issue by janpio** [apache/cordova#3]
npm introduced `package-lock.json` some time ago. Apache Cordova never decided how this file should be handled in our packages (commit to git? not commit to git? .gitignore?). 

We should define that and make the necessary changes.

**Comment by raphinesse** [comment]
I thought we decided to commit it some time ago. It's on the ToDos for the next major.

**Comment by janpio** [comment]
Well, then there should be an issue here to track the progress.

**Comment by raphinesse** [comment]
It's in "planned" [on the board for the next major](https://github.com/orgs/apache/projects/2).

So do we put meta issues :sweat_smile: here now?

**Comment by erisu** [comment]
Yes, all note cards needs to be converted into issues. I was not confident in which repo these issues were to be created. If we decided this repo then I can go head and start converting them all.

All items on that board, especially in the planned column, was decided for this coming next major. 

The items in the planning/ideas column might need more discussion but the title and content can be written as if its an actual task that will be implemented but add the discussion label. 

Once moved to the planned column, we can remove the discussion label.

@janpio @raphinesse 

Sorry I hadn't had time to send out an official email to the mailing list or bing up any of these questions.

**Comment by brodybits** [comment]
FYI we had already reached agreement in [[1]](https://lists.apache.org/thread.html/7f92561d382f143aaf49e083bbe215dcf95a3f4d8b6e3cbb6089a5f3@%3Cdev.cordova.apache.org%3E), would have liked a cross-reference.
