### ISSUE TITLE
Unable to run cordova app on Android 11

### ISSUE THREAD

**Issue by harivenkatesh-id** [apache/cordova#302]
# Bug Report
Unable to run cordova app on Android 11 but it is working well till Android 10

## Problem

- My Ionic cordova project, cordova version is 8.1.2 (cordova-lib@8.1.1)
- ionic version is 6.12.3
- Project android platform version is  android 9.0.0

My Project have below plugins

- br.com.brunogrossi.MediaScannerPlugin 0.1.3 "Media Scanner Plugin"
- cordova-plugin-app-preferences 0.99.4 "AppPreferences"
- cordova-plugin-compat 1.2.0 "Compat"
- cordova-plugin-device 2.0.2 "Device"
- cordova-plugin-file 6.0.2 "File"
- cordova-plugin-filechooser 1.2.0 "File Chooser"
- cordova-plugin-filepath 1.6.0 "cordova-plugin-filepath"
- cordova-plugin-globalization 1.11.0 "Globalization"
- cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
- cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
- cordova-plugin-media-capture 3.0.3 "Capture"
- cordova-plugin-mfilechooser 1.0.5 "Evolution36 filechooser"
- cordova-plugin-network-information 2.0.2 "Network Information"
- cordova-plugin-pasteclipboardfile 0.0.1 "Pasteclipboardfile"
- cordova-plugin-screenshot 0.1.1 "ScreenShotPlugin"
- cordova-plugin-splashscreen 6.0.0 "Splashscreen"
- cordova-plugin-statusbar 2.4.2 "StatusBar"
- cordova-plugin-webview-localstorage 0.0.1 "WebView Localstorage"
- cordova-plugin-whitelist 1.3.3 "Whitelist"
- cordova-sqlite-storage 3.4.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
- ionic-plugin-deeplinks 1.0.22 "Ionic Deeplink Plugin"
- phonegap-plugin-barcodescanner 8.0.1 "BarcodeScanner"

### What is expected to happen?

Android .apk should work on all versions of android 

### What does actually happen?

Application is launched in android 11 but stuck in splashscreen. When changed targetsdkversion from 30 to 29 application is working properly.

**Comment by erisu** [comment]
Closing because of ticket duplication: https://github.com/apache/cordova-android/issues/1355
