### ISSUE TITLE
Does not install on Windows 10 (x64) 

### ISSUE THREAD

**Issue by mysorian** [apache/cordova#306]
# Bug Report

## Problem
Not installing. Does not install on Windows 10(x64)

### What is expected to happen?
Cordova should install.

### What does actually happen?
This is what happens:
C:\>npm install -g cordova
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 487 packages, and audited 488 packages in 3m

30 packages are looking for funding
  run `npm fund` for details

6 vulnerabilities (5 moderate, 1 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice
npm notice New patch version of npm available! 8.1.0 -> 8.1.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.1.2
npm notice Run npm install -g npm@8.1.2 to update!
npm notice

C:\>npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm ERR! code ENOLOCK
npm ERR! audit This command requires an existing lockfile.
npm ERR! audit Try creating one first with: npm i --package-lock-only
npm ERR! audit Original error: loadVirtual requires existing shrinkwrap file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TestUser\AppData\Local\npm-cache\_logs\2021-10-31T06_11_51_150Z-debug.log

### Command or Code

C:\>npm install -g cordova

### Environment, Platform, Device

Windows 10 (x64) Laptop Intel Corei7

### Version information

Cordova from this site:
https://cordova.apache.org/docs/en/10.x/guide/cli/index.html

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by breautek** [comment]
Your provided output indicates that the `npm install` command was successful. If NPM wasn't successful, it would be it clear via `npm ERR` messages, which your output did not do on the `npm install` command.

`npm audit fix --force` failed because you're running the command in a non-npm module directory (e.g. it's missing `package.json` as well as the `package-lock.json` file. I know the output suggested for you to run the command to fix potential vulnerability issues, but npm audit isn't a cordova thing, it's an npm thing, so there isn't anything we can do here.

Note that this npm audit that runs when `-g` flag is used scans for all globally installed package, so the vulnerabilities reported by audit may or may be related to cordova.

You can confirm cordova is installed via running `cordova -v`.

Closing as won't fix/invalid. If you require more assistance, I welcome you to our community [Slack](http://slack.cordova.io/) channel.

**Comment by mysorian** [comment]
Thanks for the reply. Running cordova -v results in error shown:
----------------
C:\WINDOWS\system32>cordova -v
c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:77
                                throw err;
                                ^

RangeError: Maximum call stack size exceeded
    at Object.mkdirSync (node:fs:1316:19)
    at make (c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:61:12)
    at make (c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:68:5)
    at make (c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:69:12)
    at make (c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:69:12)
    at make (c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:69:12)
    at make (c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:69:12)
    at make (c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:69:12)
    at make (c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:69:12)
    at make (c:\Users\TestUser\AppData\Roaming\npm\node_modules\cordova\node_modules\conf\node_modules\make-dir\index.js:69:12)
------------------
In this directory (c:\Users\TestUser\AppData\Roaming\npm) I find, a cordova file(no extension), cordova.cmd, cordova.ps1 and a node_modules folder
----------------
In the Registry, I just find some cardova image files.
-----------------
Is there a fix for this?

**Comment by breautek** [comment]
Can you run `node -v` and tell me the output?

**Comment by mysorian** [comment]
Thanks.
It is v16.13.0

Sincerely,

Jay

**Comment by breautek** [comment]
I just tested installing on windows and I'm not reproducing your issue.

I also don't understand why your command prompt shell is located at `C:\WINDOWS\system32`, are you using an admin prompt? It's not recommended to run node/npm with admin privileges.

**Comment by mysorian** [comment]
Thanks a lot. You are right. Admin prompt has become a default by habit. I
will try without it. One thing that has complicated install issues has been
the Ransomeware protection in Windows. Anything that installs has to get
through this gate and becomes difficult as you need to give passage through
this gate.

Thanks

**Comment by racile** [comment]
so far everything is working but I just want to know if it's safe to ignore the deprecated warning also if the cordova team is working on a fix for future releases?

` cordova -v 11.0.0`

`npm WARN deprecated har-validator@5.1.5: this library is no longer supported`

`npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.`

`npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142`
