### ISSUE TITLE
Extend the feature of the framework tag in Plugin.xml

### ISSUE THREAD

**Issue by hexoh** [apache/cordova#308]
# Extend the feature of the framework tag in Plugin.xml

## Motivation Behind Feature

framework tag documentation:  [https://cordova.apache.org/docs/en/10.x/plugin_ref/spec.html#framework](https://cordova.apache.org/docs/en/10.x/plugin_ref/spec.html#framework)

On Android (as of cordova-android@4.0.0), framework tags are used to include Maven dependencies, or to include bundled library projects.

```
<!-- Depend on latest version of GCM from play services -->
<framework src="com.google.android.gms:play-services-gcm:+" />
<!-- Depend on v21 of appcompat-v7 support library -->
<framework src="com.android.support:appcompat-v7:21+" />
```

Framework can also be used to have custom .gradle files sub-included into the main project's build.gradle file:

```
<framework src="relative/path/rules.gradle" custom="true" type="gradleReference" />
```

But it can only modify build.gradle in the **`app`** directory in the cordova android project.

## Feature Description

Sometimes, we need to modify the build.gradle under the cordova project.  e.g.

I am trying to add a repository to my build.gradle file.

This is my project build.gradle file, not app folder build.gradle:

```
buildscript {
  repositories {
      google()
    }
}
```
I need to add **`jcenter()`** repo or  **`maven { url "https://maven.google.com" }`** repo to my build.gradle for example inside this:

```
buildscript {
    repositories {
        google()

        // can use the framework tag to import
        jcenter() 
        maven {
            url "https://maven.google.com"
        }
    }
}
```

I hope I can use the framework tag to modify **`allprojects`** or **`buildscript`** or **`android`** items in build.gradle.
Instead of manually adding or using hooks to implement this function every time the project is built.

**Comment by erisu** [comment]
You should be able to use the `resource-file` tag.

```xml
<resource-file src="extra.gradle" target="repositories.gradle" />
<resource-file src="extra.gradle" target="app/repositories.gradle" />
<resource-file src="extra.gradle" target="CordovaLib/repositories.gradle" />
```

Reference PRs:
* https://github.com/apache/cordova-android/pull/867
* https://github.com/apache/cordova-android/pull/1179
* https://github.com/apache/cordova-android/pull/1300

Example content of the gradle file that you would write to override the default `repositories.gradle`.

```gradle
ext.repos = {
    mavenCentral()
    google()
    jcenter()
}
```
