### ISSUE TITLE
Cordova will automatically add the permission to obtain the application list when it is packaged

### ISSUE THREAD

**Issue by lovenan** [apache/cordova#313]
# Bug Report

### What is expected to happen?
Cordova will automatically add the permission to obtain the application list when it is packaged, resulting in the audit failure when it is put on the application market. How to solve this?

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by jcesarmobile** [comment]
The only permission that cordova adds is internet permission.
If you are getting more permissions that you are not adding then it most be some plugin you have installed.
