### ISSUE TITLE
Missing Twitter Posts

### ISSUE THREAD

**Issue by teranpeterson** [apache/cordova#346]
# Bug Report

## Problem

@apachecordova on Twitter hasn't tweeted the last few releases posted to the blog. 

### What is expected to happen?

A tweet when the blog post is released. 

### What does actually happen?

Nothing. Quiet since June 8th

Not sure if this is a CI/CD problem or if someone needs to do it manually.

**Comment by timbru31** [comment]
We actually compose the Tweets here in the git repository. I believe this was simply forgotten, tanks for the hint.  
@erisu do you want to do a tweet for the media plugin release?
