### ISSUE TITLE
Geolocation getCurrentPosition is not working in some Android 12 devices

### ISSUE THREAD

**Issue by mhnimje** [apache/cordova#352]
# Bug Report

## Problem
1. Use Geolocation getCurrentPosition method - [https://cordova.apache.org/docs/en/1.8.1/cordova/geolocation/geolocation.getCurrentPosition.html](https://www.google.com/url?q=https://cordova.apache.org/docs/en/1.8.1/cordova/geolocation/geolocation.getCurrentPosition.html&sa=D&source=buganizer&usg=AOvVaw3h3I4LwBCzv126sQSjCsrU)
2. Add options - enableHighAccuracy: true,
                              maximumAge: xxxxx,
                              timeout: xxxxx
3. It gives error after timeout. Even after setting large timeout it still gives error
4. Till yesterday it was working fine
5. Issue is happening on variety of devices having Android 12

### What does actually happen?
Geolocation getCurrentPosition is not working in some Android 12 devices giving timeout issue

### Environment, Platform, Device

Android 12

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
Duplicate: https://github.com/apache/cordova-plugin-geolocation/issues/255

See: https://github.com/apache/cordova-plugin-geolocation/issues/255#issuecomment-1322124399
