### ISSUE TITLE
cordova update to 7.1.1 get error of gap_init pop up And not working properly 

### ISSUE THREAD

**Issue by sandeep2244** [apache/cordova#40]
I have updated android 3.5.1 to 7.1.1(yes it's too old) after that
 i upadated following plugins 
````
<plugin name="cordova-plugin-contacts" spec="^3.0.1" />
 <plugin name="cordova-plugin-device" spec="^2.0.2" />
 <plugin name="cordova-plugin-file" spec="^6.0.1" />
 <plugin name="cordova-plugin-inappbrowser" spec="^3.0.0" />
 <plugin name="cordova-plugin-media" spec="^5.0.2" />
 <plugin name="cordova-plugin-network-information" spec="^2.0.1" />
 <plugin name="cordova-plugin-splashscreen" spec="^5.0.2" />
 <plugin name="cordova-plugin-camera" spec="^4.0.3" />
````
then my app not working and showing popup of following messages

page at file:// says at 
gap_init:3
then 
gap:[0,"CoreAndroid","shows","blah...."]
gap:[0,"Device","shows","blah...."]
gap:[0,"File","shows","blah...."]
gap:[0,"NetworkStatus","requestAllPath","blah...."]

one by one i tap ok my index.html file doesnt load also ....
How to  solve this problem ?
Any help would be appreciate

thank you..

**Comment by brodybits** [comment]
I would highly recommend that you start with a new Cordova project, and add the components from your application one step at a time.

Alternative approach, which I would not recommend, could be to try cordova-android@4, cordova-android@5, and cordova-android@6 in sequential order.

**Comment by janpio** [comment]
+1 on what @brodybits wrote - just start a new project with current verions and add the plugins one by one.

(Also closing this as it is about cordova-android, not cordova in general and should have been created in that repo.)
