### ISSUE TITLE
`cordova plugin remove [plugin]` doesn't always work.

### ISSUE THREAD

**Issue by humblecoder** [apache/cordova#41]
`Cordova: 8.1.2 (cordova-lib@8.1.1)`

Recently, specifically, I've attempted using a few plugins that, after build, will not remove.  The script will claim to remove them, then end with something like:

```
Uninstalling 1 dependent plugins.
Uninstalling cordova-plugin-compat from android
Android Studio project detected
Uninstalling phonegap-plugin-speech-recognition from android
Uninstalling 1 dependent plugins.
Uninstalling cordova-plugin-compat from browser
Uninstalling phonegap-plugin-speech-recognition from browser
js-module uninstall called : plugins/phonegap-plugin-speech-recognition/www/browser/SpeechRecognition.js
Uninstalling 1 dependent plugins.
Uninstalling cordova-plugin-compat from ios
ENOENT: no such file or directory, open '/Users/myuser/code/cordova_projects/myproject/src-cordova/platforms/ios/www/cordova_plugins.js'
```

This happens with various plugins.  The only solution ends up being to `cordova platform remove` and re-add the platform.  Please advise.

**Comment by janpio** [comment]
What platforms are installed in the project, and which platform  version?
Does it only happen on uninstalling dependent plugins (likw `cordova-plugin-compat` for `phonegap-plugin-speech-recognition`)? Any other plugins affected?

**Comment by brodybits** [comment]
Is this still an issue?

**Comment by humblecoder** [comment]
@brodybits can't confirm.  I literally wiped my machine (for unrelated reasons) and restarted this particular project from scratch.  I can safely say I no longer experience it, but I have no idea why it was happening in the first place.  Soooooo, keep an eye out, but close it maybe?

**Comment by brodybits** [comment]
Closing now. It looks like your project was in a really inconsistent state for some reason, like something ran out of disk space or crashed near the end. Please be sure to raise a new issue, with the needed information, in case you encounter this kind of a problem someday in the future.

This issue will remain in the GitHub database and should be indexed by the search engines in case anyone encounters a similar problem in the future.

**Comment by awaism551** [comment]
In my case, when I was trying to remove one of my plugins this error was coming, downgrading my cordova version to 8.0.0 did the trick for me 

`npm install -g cordova@8.0.0`
