### ISSUE TITLE
In cordova website version drop down not yet updated

### ISSUE THREAD

**Issue by merbin2012** [apache/cordova#415]
On the website Cordova version is not yet updated, please update it to 12.0.

https://cordova.apache.org/docs/en/latest/

**Comment by Sebastiangperez** [comment]
Yes , i saw that and when i started a new app , i saw that was pulling version 12 and i thought that was using the dev version 
@merbin2012 Question , i have a problem with a build , i made a apk file , i signed , i can test it using cordova run with --device flag and works also using adb cli command , but if i want to install from whatsapp or using google drive or sending to the phone with a file manager , said app not installed , do you know what could be the problem ? 
i'm using a S10 phone , android 12 , and the app is using the latest sdk , but its just an helloworld.

**Comment by breautek** [comment]
12.x docs is released now.
