### ISSUE TITLE
cordova plugin add: "Unexpected end of JSON input"

### ISSUE THREAD

**Issue by dlbeswick** [apache/cordova#423]
# Bug Report

### What is expected to happen?
Plugins can be added using the "cordova plugin add" command

### What does actually happen?
A single line of output is displayed: "Unexpected end of JSON input"

## Information
I've tracked this issue to `cordova-lib/src/cordova/plugin/util.js`, in the "info" function. The call to `execa("npm", ...`) is returning no output. However, this doesn't seem to be an issue with "execa" because other calls such as "ls" are returning output fine.

If you change that line to the following:

    return execa('bash', ['-c', `cat <(npm ${viewArgs.join(' ')})`])

Then it works. So I suspect it's something weird with npm or node's behaviour, not flushing to stdout or something like that.

### Command or Code
`npx cordova plugin add cordova-plugin-device`

### Environment, Platform, Device

Ubuntu 22.04.2

### Version information
"node" Snap 18.16.1 (Rev 7588)
Node 18.16.1
NPM 9.5.1
Cordova 12.0.0

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by breautek** [comment]
> There is an extra "error" block at the end of the output. Very odd.

Indeed, very odd.

Does the raw command work for you? Try running: `npm view cordova-plugin-device@2.1.0 --json`

If it reproduces directly while running `npm`, then that tells us that NPM is trying to do something that it doesn't have permission to do. If the error is inside the output of execa... then I would think it's NPM that is hitting that error...

**Comment by breautek** [comment]
> Hello there Norman, running the command in a regular shell prompt works
fine. Is it something to do with the snap version of npm/node, I wonder?
I'll try to repro with a non-snap version tomorrow.

I do know that running apps under snap uses AppArmour which gives processes a fine grain control over what they can or can't do, or what directories/files they can access or can't access. I personally don't use snap cause often times these settings appears to be misconfigured for proper usage... at least that was my experience with them. But if you're running a snap version, and that's the version running in the same regular prompt, then I would have expected the issue to reproduce if it was an apparmour sandbox issue.

I use `nvm` myself, which to me is the easiest way to manage using different node versions. So if you want to try different environments, I'd give that a go.

If all else fails... I think we'll need to run the command line under the node debugger, or add print statements to try to figure out where that error is coming from exactly.
