### ISSUE TITLE
No inertial scroll on iOS with facebok plugin page

### ISSUE THREAD

**Issue by JoshTor** [apache/cordova#44]
Hi, i have an app which displays a Facebook content page with the Facebook plugin page.

On iOS, there is no inertial scrolling and i need it. I use Cordova 6.4.1 with Framework7 2.2.1.

There is the html who display it :

```
<div id="facebook" class="page-content tab tab-link">
      <iframe src="https://www.facebook.com/plugins/page.php?href=*thereIsTheValidHref*&tabs=timeline&width=340&height=500&small_header=true&adapt_container_width=true&hide_cover=true&show_facepile=false&appId" width="340" height="500" style="border:none;overflow:hidden;display:block;margin-left:auto;margin-right: auto" scrolling="yes" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
       <div class="block text-align-center">
                 <div class="preloader color-blue "></div>
        </div>
</div>
```

The iframe is well displayed. I saw that is possibly the inertial sroll on iframe with safari wich is a problem but I do not really know if it comes from cordova.
It can ?

**Comment by janpio** [comment]
> I use Cordova 6.4.1

Cordova CLI 6.4.1 does not exist.

You should also post this in cordova-ios if you are having problems on iOS: https://github.com/apache/cordova-ios/issues

**Comment by JoshTor** [comment]
Sorry it's Cordova 2.2
I'm going to publish it, but do you have an idea even if it's a cordova-ios subject ?
