### ISSUE TITLE
[Plugins] Android tests break when a new CLI is released that pins a new cordova-android version that requires a new Android target to be installed

### ISSUE THREAD

**Issue by janpio** [apache/cordova#46]
This is a rerun of a test, that passed 2 months before. So the exact same test, that used to pass, now does not any more: https://travis-ci.org/apache/cordova-plugin-contacts/jobs/431412788

The problem is that the plugin tests install the newest CLI with `npm install -g cordova`. If there is a new version of the CLI that pins a newer version of `cordova-android` that requires a newer Android target to be installed by default, this will fail as the Android targets to be installed are defined in `travis.yml`: https://github.com/apache/cordova-plugin-contacts/blob/99f9ea9ff94959c20a7823619744118725d09e31/.travis.yml#L60

So just by releasing a new CLI version with a new pinned `cordova-android`, we can make all the plugin tests for Android fail.

**Comment by janpio** [comment]
Possible solution: Install a specific version of the CLI instead of just `npm install -g cordova`: https://github.com/apache/cordova-plugin-contacts/blob/99f9ea9ff94959c20a7823619744118725d09e31/.travis.yml#L64 Disadvantage of that: All the `.travis.yml` files of the plugins have to be updated when a new CLI version is released.

**Comment by janpio** [comment]
Nothing we can do about it - either we have to specify the Android version, or the CLI version in the config.

**Comment by raphinesse** [comment]
I think having cordova-cli as a devDependency would be an easy and clean solution. Or is it only used in CI, not in local tests?

**Comment by janpio** [comment]
Yeah, this is about the Android SDK/tools version being installed by CI that has to be compatible with the pinned cordova-android version of Cordova CLI. New CLI release is automatically installed by CI, but CI config still uses older Android SDK.

**Comment by raphinesse** [comment]
Yes, but by specifying a semver range for the CLI in devDependencies that forbids major updates, that could be solved

**Comment by janpio** [comment]
Sorry, I might be missing something here:
Won't this limit what version of the CLI can be used with the plugin? 
The problem is not the plugin itself, which is perfectly fine with all Android SDK tooling (it is not relevant), but that the plugin CI has configured a specific Android SDK that can break when a new Cordova CLI is released.

**Comment by raphinesse** [comment]
> Won't this limit what version of the CLI can be used with the plugin?

Not, if you specify a version range as a devDependency or in the CI config as you previously suggested. After taking a quick look at the repo you linked, I'd say that installing a specific version in the CI config makes more sense in this case.

**Comment by janpio** [comment]
I still don't understand. Won't we have to make us update the config/package.json with each (major) CLI release vs. just sometimes when the pinned cordova-android requires a new Android SDK?

**Comment by raphinesse** [comment]
> Won't we have to make us update the config/package.json with each (major) CLI release vs. just sometimes when the pinned cordova-android requires a new Android SDK?

That is completely true. Sorry, I might have misunderstood you earlier.

Yes, we will have to decide whether we want to have scheduled maintenance at possibly shorter intervals or regular breakage at possibly longer intervals. I'd rather opt for the first Alternative, but I see the appeal in the latter, given the amount of plugins.

IMHO the underlying problem here is that we have too much overhead for simple house keeping tasks. In this case, a mono repo for plugins would probably make things easier.

**Comment by janpio** [comment]
Ok, at least my understanding of the situation was correct.

Monorepo sounds nice in theory, in practice the even worse chaos in issues and PRs would offset these benefits by a lot.

I think for now we'll keep it like it is. Future updated to the Travis config can easily be scripted as I unified them over all plugins, so this shouldn't be too much work next time.
