### ISSUE TITLE
Unable to locate DeviceSupport directory with suffix 'DeveloperDiskImage.dmg' - Xcode15.2 - Physical device 17.2

### ISSUE THREAD

**Issue by Ajitweb** [apache/cordova#463]
I have the latest Xcode 15.2  on Sonoma.
I get the above error when debugging on a physical Iphone running on 17.2 OS

According to this [flutter link](https://github.com/flutter/flutter/issues/133465)
ios-deploy will not work with Xcode15 and physical devices running 17 OS

Could not find any activity regarding this - on the ios-deploy github page

Any idea of how to solve this issue?

Thanks

**Comment by jcesarmobile** [comment]
issue on ios-deploy repository 
https://github.com/ios-control/ios-deploy/issues/588

I don't think "it won't work", it just doesn't work at the moment, but I think it should be possible to make it work.

If not, cordova-ios will have to use a different thing to run, or use devicectl directly, but devicectl only works on iOS 17 devices, so it's not perfect neither

You can create an issue on https://github.com/apache/cordova-ios/issues to track possible progress
