### ISSUE TITLE
live reload

### ISSUE THREAD

**Issue by tiagocaus** [apache/cordova#466]
When will cordova receive live reload features? This would help a lot with development. See the changes being made in real time.

**Comment by jcesarmobile** [comment]
This is not something Cordova is going to provide as it would require to ship a live reload capable server and knowing too much about your app for knowing how to serve it.
Most frameworks/bundlers already provide servers that can do live reload, so if you are using any major framework or a bundler, just run the command it provides for running in a server, and change your `config.xml` content tag to point to the live reload server, i.e. `<content src="http://localhost:8080" />`
