### ISSUE TITLE
YAML instead of XML

### ISSUE THREAD

**Issue by brodybits** [apache/cordova#57]
in project configuration & plugin specification, beyond what is specified in `package.json`

should be much easier to work with than XML & JSON

> Why?

I find YAML much easier to read, understand, and edit.

> How "easier"?

Some things I can think of right now:

General:

- no need to balance opening and closing tags (XML) or braces and brackets (JSON)
- more likely to have one item per line, easier to change one thing at a time without touching a lint that affects other things

Comparison to adding items to `package.json`:
- easier to add entries to the end of a list (no need to deal with commas)
- reduced risk that `npm` may reformat or otherwise edit non-npm items
- reduced risk of other forms of interference and other interaction with `npm`

**Comment by janpio** [comment]
(Explanation of -1: I really don't like YAML)

**Comment by brodybits** [comment]
Dear downvoters can you guys please give the reasons?

Why and how "easier" is now added to the description.

**Comment by raphinesse** [comment]
I think XML is a good fit everywhere we are using XML fragments to patch other XML files. Like when using `edit-config` to insert fragments into Manifest.xml

**Comment by brodybits** [comment]
> I think XML is a good fit everywhere we are using XML fragments to patch other XML files. Like when using `edit-config` to insert fragments into Manifest.xml

YAML can also support XML fragments: <https://stackoverflow.com/questions/1785422/how-do-you-put-html-or-xml-into-a-yaml/1786044#1786044>

> the advantages are mostly cosmetic

(easier to read) and easier to edit. I would still see this as a nice if not major advantage for Cordova users including plugin authors who may not be the most experienced in any of the major skills needed to succeed with the framework.

**Comment by raphinesse** [comment]
> YAML can also support XML fragments: https://stackoverflow.com/questions/1785422/how-do-you-put-html-or-xml-into-a-yaml/1786044#1786044

That's just an arbitrary multi-line string AFAICT. Not quite the same as an actual XML-Fragment or Node. These are also associated with a namespace. The way I see it, you would have to add the namespace in the YAML too or defer it from contextual information.

**Comment by brodybits** [comment]
Gotta say I don't understand the issue in <https://github.com/apache/cordova/issues/57#issuecomment-441734107>. People can just put what fragment they need in YAML.

**Comment by oliversalzburg** [comment]
I hope I'm not misunderstanding the suggestion, but moving to a new file with new markup just as the migration to `package.json` is about to be finalized, only to achieve debatable improvements in maintainability of the new file, seems like misplaced effort.

People have existing setups and moving to a new file format for such a crucial component in the application metadata will require everyone to work. So using improved maintainability (less work) as an argument is not convincing.

**Comment by brodybits** [comment]
I think complete migration to `package.json` will not happen anytime soon: <https://lists.apache.org/thread.html/2c038da647e2e93a9f23767287b73891cf70620f3829ed2f4ba23eab@%3Cdev.cordova.apache.org%3E>

Looks like this proposal is not worth the efforts, especially in testing and documentation, closing now.
