### ISSUE TITLE
Keyboard events not fired on pages other than index page

### ISSUE THREAD

**Issue by A7302** [apache/cordova#66]
I am working on a cordova application. I want to perform some functionality on keyboard events. But I am unable to call the events on pages other than index page. This is strange issue. Below are the version details,

Cordova : 6.0.0
Node: 8.2.1
iOS: 12.0.1

I have attached a sample application. If you click on the textbox on the first page(index page) then "keyboardWillShow" event gets called. But if you click on the "Go to Main" button and try to click on the textbox on main page no event gets fired.
[project.zip](https://github.com/apache/cordova/files/2749994/project.zip)

**Comment by jcesarmobile** [comment]
First of all, this is not the place to ask questions. You can ask on https://stackoverflow.com/ using the `cordova` tag, or join cordova slack https://slack-cordova-io.herokuapp.com/

Anyway, I did a quick look into your project and you need to include cordova.js on every page you want to use cordova plugins.
