### ISSUE TITLE
Question: Getting device timezone?

### ISSUE THREAD

**Issue by mkn20** [apache/cordova#67]
Hi,

   As the cordova-plugin-globalization is said to be deprecated, how **exactly** ECMA Internationalization API can then be used to get the device timezone? So, in essence, what is the equivalent (using ECMA Internationalization API)  of navigator.globalization.getDatePattern and using date.timezone from the result to find the device timezone? It is not apparent from the migration guide (https://cordova.apache.org/news/2017/11/20/migrate-from-cordova-globalization-plugin.html) and so an example would help!

Thanks in advance and regards

**Comment by globules-io** [comment]
So we faced the same issue and we worked around it by getting location (lat/lng) of phone then convert position to timezone (via Google timezone API). There is no built in method anymore within Cordova I believe...

**Comment by raphinesse** [comment]
Sorry for the late reply, but this should do it: https://stackoverflow.com/a/34602679/380229
