### ISSUE TITLE
$ANDROID_SDK_ROOT support?

### ISSUE THREAD

**Issue by vtaliar** [apache/cordova#68]
Hi,

$ANDROID_HOME is now deprecated and might be removed soon. 

For more details please refer to [this page](https://developer.android.com/studio/command-line/variables).

Cordova@8.1.2 still requires $ANDROID_HOME to be set.

Is there a plan to support $ANDROID_SDK_ROOT over $ANDROID_HOME? If so, when it is going to happen?

Best regards,
Volodymyr

**Comment by janpio** [comment]
Step 1: Create an issue at https://github.com/apache/cordova-android :)

**Comment by brodybits** [comment]
I just raised apache/cordova-android#617 to track this issue, closing it here. Unfortunately I cannot make any promises when we will get a chance to solve this one, hoping we can solve it soon. Thanks @vtaliar for reporting.
