### ISSUE TITLE
Use c8 for coverage

### ISSUE THREAD

**Issue by brodybits** [apache/cordova#70]
I just discovered [`bcoe/c8`](https://github.com/bcoe/c8) ([`c8`](https://www.npmjs.com/package/c8)) which does NYC/Istanbul code coverage using [Node.js v8 coverage](https://nodejs.org/dist/latest-v10.x/docs/api/cli.html#cli_node_v8_coverage_dir). This would require Node.js version 10 but I cannot see why we would need to run coverage on older Node.js versions.

I would NOT recommend we do this before Cordova 9 is finished.

Discovered via tapjs/node-tap#493

**Comment by janpio** [comment]
What is the disadvantage of using nyc/istanbul? Speed as mentioned in the linked issue?

**Comment by brodybits** [comment]
> Speed as mentioned in the linked issue?

Yes. Maybe not major but I would favor choosing the more efficient tooling if there are no other factors against it.

**Comment by raphinesse** [comment]
I would argue that we have enough work in our hands and performance is not a problem at the moment. Furthermore, nyc is well maintained AFAICT and its adoption is much greater than that of c8. Interesting to see that there are alternatives though.

Who knows maybe nyc will even start to use c8 itself if it is that much faster. This way we wouldn't have to do any of the work :smile: 

I would propose to do do nothing and close this issue. Objections?
