### ISSUE TITLE
Cannot prepare after changing product name

### ISSUE THREAD

**Issue by brodybits** [apache/cordova#71]
If I would change the app id and name in `config.xml`, then `cordova prepare ios` gives me the following result:

```
The product name change (<name> tag) in config.xml is not supported dynamically.
To change your product name, you have to remove, then add your ios platform again.
Make sure you save your plugins beforehand using `cordova plugin save`.
[...]
```

Not so nice for usability.

**Comment by jcesarmobile** [comment]
As far as I remember, changing the name required a lot of project changes that could easily break the Xcode project and it was easier to just nuke everything and re add the platform. 
As platforms are build artifacts I don't see this as a big usability problem. 

Anyway, we might want to revisit, nowadays most values are picked from a variable and maybe we can just set that variable ¿`PRODUCT_NAME`?

**Comment by purplecabbage** [comment]
Original thread here: https://issues.apache.org/jira/browse/CB-11712
IMHO, this should not happen frequently enough to justify the work to fix it.
The work around is not terrible, and we save all the plugins now, so really it is just rm/add.

**Comment by oliversalzburg** [comment]
Seems to me like the result is perfectly fine. You get a clear message what to do and if you do _that_, your problem is resolved. Perfectly suited for the frequency at which I assume this use case comes up.
