### ISSUE TITLE
[Plugins] Drop Node 4 support

### ISSUE THREAD

**Issue by timbru31** [apache/cordova#72]
As per #5, but this time for plugins:

### Goal
- Drop Node 4 Support

List of active core plugins

- [x] cordova-plugin-battery-status (https://github.com/apache/cordova-plugin-battery-status/pull/73)
- [ ] cordova-plugin-camera
- [ ] cordova-plugin-device
- [ ] cordova-plugin-dialogs
- [ ] cordova-plugin-file
- [ ] cordova-plugin-geolocation
- [ ] cordova-plugin-inappbrowser
- [ ] cordova-plugin-media
- [ ] cordova-plugin-media-capture
- [x] cordova-plugin-network-information (https://github.com/apache/cordova-plugin-network-information/pull/87)
- [x] cordova-plugin-screen-orientation (https://github.com/apache/cordova-plugin-screen-orientation/pull/45)
- [ ] cordova-plugin-splashscreen
- [x] cordova-plugin-statusbar (https://github.com/apache/cordova-plugin-statusbar/pull/124)
- [x] cordova-plugin-vibration (https://github.com/apache/cordova-plugin-vibration/pull/76)
- [x] cordova-plugin-whitelist (no CI or tests yet, see https://github.com/apache/cordova-plugin-whitelist/issues/29)
- [x] cordova-plugin-wkwebview-engine (https://github.com/apache/cordova-plugin-wkwebview-engine/pull/91)

**Comment by timbru31** [comment]
Due to major releases I've unchecked all plugins since the CI won't work currently with those outdated Xcode images nor the unchecked licenses for Android SDKs. First candidate to cleanup this, too, is: https://github.com/apache/cordova-plugin-vibration/pull/76

For reference, broken TravisCI builds: https://travis-ci.org/apache/cordova-plugin-vibration/jobs/523723056#L2302 & https://travis-ci.org/apache/cordova-plugin-vibration/jobs/523723055#L2209

**Comment by brodybits** [comment]
I would not favor supporting Node.js version 6 for much longer, considering that its scheduled EOL is just a few days away.

**Comment by timbru31** [comment]
+1 that’s what I’ve though of, too :)

**Comment by janpio** [comment]
I'll copy over what I wrote at https://github.com/apache/cordova-plugin-vibration/pull/76#issuecomment-486153423:

> We have a passing state at paramedic, so now we'll see what happens with the first plugins. https://github.com/apache/cordova-plugin-inappbrowser/pull/465 is the other first try to adapt the configuration from there.

When we have that (currently tests are failing on iOS 12.2 - not sure if this is a problem with the plugin or with the test setup yet) and vibration in a good state, we can start rolling that out to more plugins and see what happens.

**Comment by janpio** [comment]
travis.yml changes have been created as PRs for all plugins. This included going to node 6 for all of these configurations. I wrote a dev mailing list message which gives an overview: https://lists.apache.org/thread.html/959ebe1683ac8ac10013d70a514bdf213ac6935ffd28fd045b269ab6@%3Cdev.cordova.apache.org%3E

Now we probably only need PRs for appveyor.yml and possibly updated to package.json.

**Comment by janpio** [comment]
Plugins were released with green CI, so this should already be taken care of for all plugins - correct?

**Comment by erisu** [comment]
@janpio I did a quick review though those remaining plugin's master branch and this is the results:

**Completed and can be updated in ticket  desc.**
* cordova-plugin-camera (travis: 8 appveyor: 6)

**Unfinished and need PRs**
* cordova-plugin-device (travis: 8 appveyor: 4)
* cordova-plugin-dialogs (travis: 8 appveyor: 4)
* cordova-plugin-file (travis: 8 appveyor: 4)
* cordova-plugin-geolocation (travis: 8 appveyor: 4)
* cordova-plugin-inappbrowser (travis: 8 appveyor: 4)
* cordova-plugin-media (travis: 8 appveyor: 4)
* cordova-plugin-media-capture (travis: 8 appveyor: 4)
* cordova-plugin-splashscreen (travis: 8 appveyor: 4)

AppVeyor could actually be bumped to node 8 to match with Travis CI configs. If that is preferred, then camera and maybe the already completed items would need revisits.

**Comment by timbru31** [comment]
Closing in favor of #79
