### ISSUE TITLE
"There was an error processing the request.Reload" page getting loaded when trying to login to FitBit app InAppBrowser in outsystem project

### ISSUE THREAD

**Issue by jyothishnarayan** [apache/cordova#77]
### Issue Type

- [x ] Bug Report
- [ ] Feature Request
- [ x] Support Question

## Description
I am using the FitBit API for integrating FitBit app in outsystems project. When user credentials entered and login is completed, just before the success page, I am getting an error page saying "There was an error processing the request.Reload". This page stays for few seconds and the login gets successful.This issue is happening in lower end Android devices. Why this reload screen is getting displayed?

### Environment, Platform, Device
FitBit API integration in crossplatform App developed using Outsystems version 10.

### Version information

- [ x] I searched for already existing GitHub issues about this
- [x ] I updated all Cordova tooling to their most recent version
- [x ] I included all the necessary information above

**Comment by janpio** [comment]
Does your app actually use Cordova, your description doesn't mention it at all.  
What exactly is Outsystems?

If this only happens on Android, https://github.com/apache/cordova-android would be the better repository to report this anyway. But to be honest, it sounds more like a usage problem than a bug - so StackOverflow or Slack might be the better place to ask again.
