### ISSUE TITLE
Add Node 12 & Drop Node 6 & 8 Support

### ISSUE THREAD

**Issue by erisu** [apache/cordova#79]
# Feature Request
I would like to start discussing and planning for:
- Dropping `Node 6` Support
- Dropping `Node 8` Support
- Adding `Node 12` Support

## Motivation Behind Feature
The Node team currently has documented: 
- Node 6's End of Life: 2019-04-30
- Node 8's End of Life: Targeted date December 2019
- Node 12's Initial Release: Targeted date April 23rd 2019

You can read more about Node's release schedule [here](https://github.com/nodejs/Release).

## Feature Description

- [x] Public Announcement via Blog Post

### **May 2019?**

- [x] Update AppVeyor/Travis CI to test with Node.js 6.x, 8.x, 10.x, and 12.x.
- [x] Update requirement check and notify users of Node.js 6.x deprecation. https://github.com/apache/cordova-cli/pull/454

### **Fall 2019**

- [x] Update requirement check and notify users of Node.js 8.x deprecation. https://github.com/apache/cordova-cli/pull/458

### **Winter 2019**

- [x] Removed Node.js 6.x support.
- [x] Removed Node.js 8.x support.
- [x] Added Node.js 12.x  support.
- [x] Platforms, tools, and core libraries to bump up a major version.
- [x] Update AppVeyor/Travis CI to test only Node.js 10.x, and 12.x.

## Alternatives or Workarounds
- Undefined

### Platforms

- [x] cordova-android
- [x] cordova-browser
- [x] cordova-electron
- [x] cordova-ios
- [x] cordova-osx
- [x] cordova-windows

### Plugins

- [x] cordova-plugin-battery-status (https://github.com/apache/cordova-plugin-battery-status/pull/80/)
- [x] cordova-plugin-camera (https://github.com/apache/cordova-plugin-camera/pull/576)
- [x] cordova-plugin-device (https://github.com/apache/cordova-plugin-device/pull/120)
- [x] cordova-plugin-dialogs (https://github.com/apache/cordova-plugin-dialogs/pull/136)
- [x] cordova-plugin-file (https://github.com/apache/cordova-plugin-file/pull/384)
- [x] cordova-plugin-geolocation (https://github.com/apache/cordova-plugin-geolocation/pull/193)
- [x] cordova-plugin-inappbrowser (https://github.com/apache/cordova-plugin-inappbrowser/pull/659)
- [x] cordova-plugin-media (https://github.com/apache/cordova-plugin-media/pull/274)
- [x] cordova-plugin-media-capture (https://github.com/apache/cordova-plugin-media-capture/pull/165)
- [x] cordova-plugin-network-information (https://github.com/apache/cordova-plugin-network-information/pull/104)
- [x] cordova-plugin-screen-orientation (https://github.com/apache/cordova-plugin-screen-orientation/pull/61)
- [x] cordova-plugin-splashscreen (https://github.com/apache/cordova-plugin-splashscreen/pull/252)
- [x] cordova-plugin-statusbar (https://github.com/apache/cordova-plugin-statusbar/pull/182)
- [x] cordova-plugin-vibration (https://github.com/apache/cordova-plugin-vibration/pull/86)
- [x] cordova-plugin-whitelist (https://github.com/apache/cordova-plugin-whitelist/pull/52)
- [x] cordova-plugin-wkwebview-engine (https://github.com/apache/cordova-plugin-wkwebview-engine/pull/136)

### Tooling

- [x] cordova-cli
- [x] cordova-coho
- [x] cordova-common
- [x] cordova-create
- [x] cordova-fetch
- [x] cordova-js
- [x] cordova-lib
- [x] cordova-node-xcode (https://github.com/apache/cordova-node-xcode/pull/90)
- [x] cordova-paramedic (https://github.com/apache/cordova-paramedic/pull/198)
- [ ] cordova-plugin-test-framework (https://github.com/apache/cordova-plugin-test-framework/pull/48)
- [x] cordova-plugman
- [x] cordova-serve

_Low Priority & Non-blocker:_
- [ ] cordova-docs

_Excluded:_ 
* `cordova-app-hello-world`
* `cordova-test-platform`
* `cordova-mobile-spec`
* `cordova-status`
* `cordova`
* any unused, outdated, or deprecated repos

**Comment by janpio** [comment]
Some data from telemtry.cordova.io to enable us to make an informed decision:

### New users:

Node Major Version | New Users |  
-- | -- | --
12 | 8 | 0,01%
11 | 7491 | 9,76%
10 | 28488 | 37,11%
9 | 1760 | 2,29%
8 | 24547 | 31,97%
7 | 1003 | 1,31%
6 | 5800 | 7,56%
5 | 146 | 0,19%
4 | 7509 | 9,78%
0 | 18 | 0,02%
  | 76770 |  100%

Users with node <8: 18,86%


### All users:

Node Major Version | Users |  
-- | -- | --
12 | 8 | 0,00%
11 | 16061 | 9,33%
10 | 59900 | 34,81%
9 | 5250 | 3,05%
8 | 62589 | 36,37%
7 | 2194 | 1,27%
6 | 13085 | 7,60%
5 | 333 | 0,19%
4 | 12607 | 7,33%
0 | 59 | 0,03%
  | 172086 | 100%

Users with node <8: 16,43%

### Context

I included node 7 here in the calculations which node version to drop, as it was EOL on 2017-06-30 already.

All data from the last 30 days, the absolute numbers don't really have a specific meaning, as well as "Users" is undefined. The relative data is the important bit.

---

The amount of users to be "left behind" would be similar to what we did/do with Cordova CLI 9, where we also remove ~8-10% of current and new user's node version.

So it would definitely hit a lot of people, but as this is based on official EOL and end of maintenance, this should be a positive thing for them.

**Comment by brodybits** [comment]
As a nit-picking comment I would favor adding Node.js 12 and dropping Node.js 6 in separate commits in each repo. I would also favor adding Node.js 12 *before* dropping Node.js 6.

I think this would make it a little easier to cherry-pick the changes into a maintenance release branch if needed.

**Comment by erisu** [comment]
**Blog Announcement Reference:** https://github.com/apache/cordova-docs/pull/965
--> Updated Image Timeline: https://github.com/apache/cordova-docs/pull/967

**Comment by brodybits** [comment]
From apache/cordova-android#781 there are comments that we may want to drop Node.js 8 support at the same time. This should probably be discussed on the list (<dev@cordova.apache.org>).

**Comment by erisu** [comment]
This had already been discussed and casually voted on. Blog post is already released.

- [Mailing List Thread](https://lists.apache.org/thread.html/de3f47975bfe2a41f0e0145829ec1058225a0fe789fb862859026389@%3Cdev.cordova.apache.org%3E)
- [Blog Post](https://cordova.apache.org/news/2019/04/11/nodejs-6.x-8.x-deprecation-timeline.html)

**Comment by erisu** [comment]
Closing as complete. The important repos were completed and remaining has PRs
