### ISSUE TITLE
Fullscreen lost on user seizure

### ISSUE THREAD

**Issue by GautierDele** [apache/cordova#81]
# Bug Report

## Problem

Hello, I'm having some trouble using Apache Cordova's Fullscreen preference on user seizure

### What is expected to happen?

On user seizure, status and bottom navigation bar are both showing and after the seizure they should both disappear.

### What does actually happen?

After seizure pannel is disappearing, they are both staying.

### Command or Code

config.xml:
```xml
<preference name="Fullscreen" value="true" />
```

### Environment, Platform, Device

Android Pie on Samsung Galaxy S9+

### Version information

>   "cordova-android": "^7.1.4",
>   "cordova-ios": "^4.5.5",
>   "cordova-plugin-screen-orientation": "^3.0.1",
>   "cordova-plugin-whitelist": "^1.3.3",
>    cordova -v: 8.1.2 (cordova-lib@8.1.1)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
What is "user seizure"?
Does this only affect `cordova-android`? Then this should probably be reported at https://github.com/apache/cordova-android

**Comment by GautierDele** [comment]
Oh sorry, I meant "user entry" by "user seizure"
I was also wondering if it was only with `cordova-android`, I can't actually test it on other platforms, this is why I posted it here.

**Comment by janpio** [comment]
Please report this for cordova-android, maybe someone can investigate over there then. Thanks.
