### ISSUE TITLE
[Plugins] Saucelabs will deprecate "old" OS and Appium versions

### ISSUE THREAD

**Issue by janpio** [apache/cordova#82]
This might affect us:

> Sauce Labs will discontinue support for the following operating systems and Appium versions on Sauce emulators and simulators on April 4th.
> 
> * iOS 9.3, 10.0 and 10.2
> * Android 4.4 and 5.0
> * Appium versions 1.7.2 and below on both iOS and Android

https://wiki.saucelabs.com/display/DOCS/2019/03/07/Announcing+End+of+Life+for+old+OS+versions+on+Sauce+emulators+and+simulators

**Comment by janpio** [comment]
Yes, it does: 

- Currently the plugins _only_ run iOS 9.3 and 10.0. 
- They also run Android 4.4.
- It seems we are also using Appium version 1.6.4 explicitly in some of the configurations

So: Jackpot.

Appium version can probably be configured via a PR to paramedic, but the actual OS versions being tested have to be configured in `.travis.yml` in each plugin repo. Yay.

**Comment by janpio** [comment]
First step is to update paramedic (our test runner) itself to actually support all relevant newer OS/version combinations and tests them itself: https://github.com/apache/cordova-paramedic/pull/97

**Comment by janpio** [comment]
April 4th has gone, the mentioned device/version combinations still seem to work (sometimes). Well...

**Comment by timbru31** [comment]
Besides that, all xcode8 test will no longer work due to:
> Cordova needs xcodebuild version 9.0.0 or greater, you have version 8.0. Please install version 9.0.0 or greater from App Store

Why? Because the tests install `npm i -g cordova` and will receive CLI v9 which itself will install cordova-ios 5.0.0 which set the minimum version to Xcode9: https://github.com/apache/cordova-ios/blob/master/bin/templates/scripts/cordova/lib/check_reqs.js#L29

🙃

**Comment by janpio** [comment]
Fortunately that one is trivial to fix - just upgrade the image used by Travis.

Unfortunately https://github.com/apache/cordova-paramedic/issues/119 is not.

**Comment by janpio** [comment]
iOS 10 is finally gone as well and throwing errors.

**Comment by janpio** [comment]
Platforms removed via rollout of https://github.com/apache/cordova-paramedic/blob/master/.travis.yml that is in progress.

**Comment by janpio** [comment]
Android 4.4 seems to be gone now as well - and I forgot that in the updated `.travis.yml` :/

**Comment by janpio** [comment]
The updated Travis configuration and thus SauceLabs platforms have been rolled out to all plugin repositories. Some platforms had to be moved to future PRs as the tests are breaking on them, but that was more or less expected:

https://github.com/apache/cordova-plugin-camera/pull/469
https://github.com/apache/cordova-plugin-file/pull/328
https://github.com/apache/cordova-plugin-geolocation/pull/160
https://github.com/apache/cordova-plugin-inappbrowser/pull/493
https://github.com/apache/cordova-plugin-media/pull/237
https://github.com/apache/cordova-plugin-wkwebview-engine/pull/104

We can work through these via the individual issues I created, see the PRs.
