### ISSUE TITLE
Random build failures due to fs-extra defect

### ISSUE THREAD

**Issue by brodybits** [apache/cordova#83]
Random build failures due to fs-extra defect in: jprichardson/node-fs-extra#657

reported by @oliversalzburg in apache/cordova-common#64

also discussed in the following places:
- <https://github.com/apache/cordova-lib/pull/613#issuecomment-474377440>
- apache/cordova-android#692 / apache/cordova-android#693

The discussion is already in apache/cordova-common#64. I suspect we should keep it there for now. I think this issue needs to be reported and tracked at the top level since it affects multiple Cordova packages.

**Comment by oliversalzburg** [comment]
I really hope we can find a solution in fs-extra, but the maintainers are having a hard time deciding on what the right path to go is and there seems to be no hurry to work out a solution.

I previously had a similar experience when I tried to resolve the "link copy" issue, which is still open.

If someone has a suggestion on how to mitigate this issue in Cordova, I'd be glad to hear it. I currently see no other option than to implement a separate copy command that doesn't have an inode equality check (or a proper one). Which would be disappointing as that's the opposite of what you want when using such a library.

**Comment by brodybits** [comment]
I can think of a couple ideas:

- try using built-in fs.copySync from Node.js (I cannot tell if it would break anything else or not without some testing and analysis)
- publish a new "copy" or "copy-sync" package with the JavaScript that does what we want

**Comment by dimitriscsd** [comment]
How is this coming along? Any decisions been taken? Fs extra is about to release v8 with apparently a workaround for this issue.

**Comment by brodybits** [comment]
Please take a look at the recent comments in apache/cordova-common#64, where you should see the answer so far.

If we *do* incorporate a new fs-extra release, I suspect we would do a pipelined release of a number of components including `cordova-common`, some if not all Cordova platform components, `cordova-lib`, and `cordova-cli`.

**Comment by brodybits** [comment]
I am now closing this issue as a duplicate of #121 which was just transferred from cordova-common.
