### ISSUE TITLE
Remove deprecated `engineStrict` from packages.json

### ISSUE THREAD

**Issue by janpio** [apache/cordova#86]
This was done before, 

> [CB-12665](https://issues.apache.org/jira/browse/CB-12665): removed `engineStrict` as it is no longer supported

but some repositories slipped through:

https://github.com/search?q=org%3Aapache+engineStrict&type=Code

- [x] cordova-create
- [x] cordova-windows
- [x] cordova-browser
- [x] cordova-ios
- [x] cordova-plugman

**Comment by timbru31** [comment]
I've sent some PRs

**Comment by janpio** [comment]
Thanks.
