### ISSUE TITLE
Cordova CLI 9.0.0 - Missing RES Folder

### ISSUE THREAD

**Issue by brainssolutions** [apache/cordova#90]
### Command or Code
cordova create MyApp com.myapp.app MyApp

## Problem
When you try to create a new project, the folder  "Res " is not created

### Version information

Cordova: Cordova CLI 9.0.0
Node : Node 8.12.0
OS : macOS Mojave 10.14.4

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
What `RES` or `Res ` folder are you referring to? Where should this be created? What would this be used for? Where does this cause problems?

**Comment by brainssolutions** [comment]
Hi @janpio,
I mean the folder  "res" in the project folder , where you will enter the icons of the app and SplashScreen.

**Comment by raphinesse** [comment]
This has been deliberately removed from our app template. See [CB-14098](https://issues.apache.org/jira/browse/CB-14098) and https://github.com/apache/cordova-app-hello-world/pull/21.

**Comment by raphinesse** [comment]
@brainssolutions The `res` folder is not special in any way. You can also name the folder `resources` as you have to specify the paths to the icons in your `config.xml` anyway.

That being said, the _double_ double quoted attributes in your XML snippet look dubious.
Another thing to watch out for: Those paths are relative to the project root, not the `www` folder.

**Comment by aacassandra** [comment]
manual added and configuring your config.xml

**Comment by evilcoder04** [comment]
I just updated to Cordova CLI 10, and when I try to `cordova build android` the default asset images of cordova are being automatically included to platforms/android/app/src/main/res.

This behavior causes my app to use the default icon of cordova instead of the one I specified myself.

**Comment by erisu** [comment]
Locking this thread as this issue had been resolved and the last comment was off-topic.
