### ISSUE TITLE
Add OGX.JS as Framework

### ISSUE THREAD

**Issue by globules-io** [apache/cordova#92]
# Feature Request

## Motivation Behind Feature

New JavaScript framework for Cordova - Please add a link from homepage

## Feature Description

Please add link from Cordova site homepage to 
https://github.com/globules-io/OGX.JS/wiki

**Logos can be found here:**
Color : https://drive.google.com/file/d/1NYWktWlilxIxjvXs65iYGsrLMGkW44di/view?usp=sharing
B&W : https://drive.google.com/file/d/1Q4cWBwR0C33_mWzq957k413MN04h4Fpb/view?usp=sharing

**Description:**
OGX.JS is a JavaScript framework to rapidly create mobile (Android, iOS), desktop (Android ChromeOS) and web applications.

**Comment by brodybits** [comment]
Thanks @globules-io. Given the sheer volume of existing web JavaScript libraries and frameworks, I would favor a quick list of unique benefits, how it compares to some close alternatives, and how it compares to some well-known frameworks such as Angular/Vue/React.

**Comment by globules-io** [comment]
@brodybits have you had time to check out the 47 pages of the wiki? I will try to compile a bullet point list. This was made especially for Webview with Cordova in mind, unlike Angular/React. Didn't think there was enough framework for Cordova... What a weird comment with all due respect.

**Comment by globules-io** [comment]
- OGX.JS does not rely on any tech stack, it is highly portable and does not required any compiler
- OGX.JS has templating operations unlike other frameworks, with temporary properties and global var support and loop operations
- OGX.JS supports template-binding to object properties (render different objects within the same list)
- OGX.JS has all the components already built-in so you don't need to code as much as other frameworks to output a pro grade app
- OGX.JS data handling is inspired by MongoDB (via OGX.List or MongOGX)
- OGX.JS allow binding between components to filter/sort/display
- OGX.JS can transform and render complex datasets via different components with one line, including data trees
- OGX.JS is scope based and can render different data depends on the user scope
- OGX.JS is mobile first and has a multitude of components supporting drag, swipe, swipe reveal, reorder
- OGX.JS supports simple popups, tabbed popups, windows and views
- OGX.JS supports multiple virtual apps within an app via a Threater or "stage explorer"
- OGX.JS handles loading, storing and routing via a single app.json config, including preloading fonts, sounds, images, html templates..
- OGX.JS supports fields and form binding including restriction, validation and population
- OGX.JS has built in geo operations to work with maps
- OGX.JS has built in color tools
- and all of the other good stuff a framework is expected to have (history management, locking, dynamic views, display objects and much more).

**Comment by globules-io** [comment]
For your consideration
https://globules.io/framework

**Comment by globules-io** [comment]
OGX.JS is now on NPM. 

    ```
 cordova create myfolder com.company
     cd myfolder
     npm i @globules-io/ogx.js
```

**Comment by globules-io** [comment]
So is it a yes/no? Why? What don't you like?

**Comment by globules-io** [comment]
Get we get an update please?

**Comment by globules-io** [comment]
Get we get an update please?

**Comment by globules-io** [comment]
Nevermind, will create a pull request on the website
