### ISSUE TITLE
Can't tap to edit on input text on Android 9 Pie

### ISSUE THREAD

**Issue by didinj** [apache/cordova#96]
# Bug Report

### What is expected to happen?
Input text should working normally as previous Cordova version (@8.0.0)

### What does actually happen?
Can't tap to edit or fill input text in the login form on Android 9 Pie. But, after tap on the top of the screen, the input text can edit or fill.

### Command or Code

`ionic cordova run android`

### Environment, Platform, Device

MacOS Mojave, Android 9 Device

### Version information

Ionic:

   ionic (Ionic CLI)  : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 9.0.0
   Cordova Platforms     : android 8.0.0, ios 5.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, (and 10 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/didin/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 7.0.0
   NodeJS            : v10.15.1 (/usr/local/bin/node)
   npm               : 6.8.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2 Build version 10E125

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
This seems to be a problem with `cordova-android`, please report this over at https://github.com/apache/cordova-android. Thanks.

**Comment by StefanRein** [comment]
@didinj It is a problem with ionic 3.
See here: https://github.com/apache/cordova-android/issues/804
