### ISSUE TITLE
App not scaling correctly on android

### ISSUE THREAD

**Issue by RaZ0r1994** [apache/cordova#98]
### Issue Type

- [X] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Information
I cant get the app to use the full height of the device. The only topics i found were referring to ios.

### Environment, Platform, Device
Android version 8.1.0
Phone is Honor 8x

Apache Cordova toolset version: 6.3.1
![cordova](https://user-images.githubusercontent.com/39921982/56023411-0e28f000-5d0e-11e9-8ea6-56647e83cb1e.jpeg)

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
Cordova Android has its own repository. Please report over there: https://github.com/apache/cordova-android Thanks.
