### ISSUE TITLE
Please add Application Preferences as a core plugin

### ISSUE THREAD

**Issue by svenyonson** [apache/cordova#99]
# Feature Request

## Motivation Behind Feature
Just about any mobile application can benefit from a native preferences pane. There is such a plugin currently: `https://github.com/apla/me.apla.cordova.app-preferences`

Unfortunately, the repo appears to be abandoned with no support. It does not work using the latest platforms/frameworks. (xcode 10, cordova 8.0)

This really needs to be a CORE plugin, so that this functionality will always be available.

## Feature Description

The plugin will allow users to specify the application preference definitions in JSON. (these ultimately wind up in the native settings.bundle). Then, the plugin allows the application to read/write values from preferences. When accessing preferences through the system interface (eg. ios ->Settings -> Application), the accessed settings reflect whatever changes were made from the application.

## Alternatives or Workarounds

Unfortunately, with the existing plugin broken, there is none. Dead in the water

**Comment by brodybits** [comment]
I think that all Cordova maintainers (including myself) are already overloaded without having to maintain an Application Preferences plugin. I would favor that someone or some people who are so motivated pick up the work and continue with a new plugin name. Please feel free to announce it here or on one of our mailing lists.

**Comment by jcesarmobile** [comment]
We are not planning on adding new core plugin, as brodybits said, we are already overloaded with the existing ones.
